import { initializeApp, getApps } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js';
import { getAuth, GoogleAuthProvider, signInWithPopup, signInWithRedirect, getRedirectResult, signInAnonymously, onAuthStateChanged } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-auth.js';
import { getFirestore, doc, setDoc, getDoc, updateDoc, collection, onSnapshot, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js';

const script=document.currentScript;
const PROJECT=script?.dataset.project||'mesa';
const ROOT=script?.dataset.root||'carroforte';
const TITLE=script?.dataset.title||'MOSAICO';
const READY_EVENT=script?.dataset.readyEvent||'mosaico-room-ready';
const CONFIGS={
  mesa:{apiKey:'AIzaSyA160bkgHBrYBwvIxlENax-aAyLWPMaOU4',authDomain:'mosaico-game.firebaseapp.com',projectId:'mosaico-game',storageBucket:'mosaico-game.appspot.com',messagingSenderId:'703343424116',appId:'1:703343424116:web:e6990b5c00d43aca6e9721'},
  noite:{apiKey:'AIzaSyA160bkgHBrYBwvIxlENax-aAyLWPMaOU4',authDomain:'mosaico-noite.firebaseapp.com',projectId:'mosaico-noite',storageBucket:'mosaico-noite.firebasestorage.app',messagingSenderId:'703343424116',appId:'1:703343424116:web:e6990b5c00d43aca6e9721'}
};
const app=getApps().find(a=>a.name===`dragon-${PROJECT}`)||initializeApp(CONFIGS[PROJECT],`dragon-${PROJECT}`);
const auth=getAuth(app),db=getFirestore(app);
const ALPH='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
let role='',code='',players=[],room=null,unsubRoom=null,unsubPlayers=null;
const q=new URLSearchParams(location.search).get('sala');

function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function gerar(){let s='';for(let i=0;i<6;i++)s+=ALPH[Math.floor(Math.random()*ALPH.length)];return s;}
function roomRef(c){return doc(db,ROOT,c)}
function playerRef(c,uid){return doc(db,ROOT,c,'jogadores',uid)}
function joinUrl(c){const u=new URL(location.href);u.search='';u.searchParams.set('sala',c);return u.toString();}
function qr(c){const url=joinUrl(c);if(window.MosaicoQR)return window.MosaicoQR.svg(url,{nivel:'M',margem:4,rotulo:'QR para entrar na sala'});return `<div class="room-qr-fallback">${esc(c)}</div>`;}
function css(){const st=document.createElement('style');st.textContent=`
#dragonRoomGate{position:fixed;inset:0;z-index:99999;background:radial-gradient(900px 600px at 50% -10%,#16242a 0,transparent 55%),#061014;color:#f0eadc;font-family:Inter,system-ui,sans-serif;overflow:auto}.dr-shell{width:min(620px,calc(100% - 28px));margin:auto;padding:max(24px,env(safe-area-inset-top)) 0 max(36px,env(safe-area-inset-bottom))}.dr-brand{font-size:12px;letter-spacing:.22em;text-transform:uppercase;color:#e8a94a;font-weight:800}.dr-card{margin-top:18px;padding:20px;border:1px solid #31404a;border-radius:14px;background:linear-gradient(160deg,#121c22,#080e12);box-shadow:inset 0 1px rgba(255,255,255,.06),0 7px 0 #020507,0 22px 45px rgba(0,0,0,.45)}.dr-card h1,.dr-card h2{font-family:Georgia,serif;margin:.25rem 0 .6rem}.dr-card h1{font-size:clamp(38px,10vw,62px);line-height:.95}.dr-card p{color:#afbdc5;line-height:1.5}.dr-btn{width:100%;min-height:52px;margin-top:10px;border:0;border-radius:10px;padding:12px 14px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;cursor:pointer;background:linear-gradient(#ffc266,#dd8b2e);color:#1b1005;box-shadow:inset 0 1px #ffe2b4,0 5px 0 #6a3712}.dr-btn.secondary{background:linear-gradient(#24343d,#142128);color:#dce8ed;box-shadow:inset 0 1px rgba(255,255,255,.08),0 5px 0 #030709;border:1px solid #334750}.dr-input{width:100%;min-height:50px;margin-top:10px;border-radius:9px;border:1px solid #3a4c56;background:#071014;color:#fff;padding:12px;font-size:17px}.dr-code{font:800 clamp(40px,12vw,70px)/1 monospace;letter-spacing:.13em;color:#ffc46b;text-align:center;margin:12px 0}.dr-qr{width:min(300px,80vw);margin:14px auto;background:white;padding:10px;border-radius:12px}.dr-qr svg{display:block;width:100%;height:auto}.dr-list{display:grid;gap:8px;margin-top:14px}.dr-player{padding:10px 12px;border:1px solid #2d3b43;border-radius:9px;background:#0a1318;display:flex;justify-content:space-between;gap:10px}.dr-note{font-size:13px;color:#82959f}.dr-error{margin-top:12px;padding:10px;border-left:3px solid #e56b52;background:#28110e;color:#ffd4ca}.room-qr-fallback{color:#111;font:800 36px monospace;text-align:center;padding:40px 5px}
`;document.head.appendChild(st)}
function gate(){let el=document.getElementById('dragonRoomGate');if(!el){el=document.createElement('div');el.id='dragonRoomGate';document.body.appendChild(el)}return el}
function menu(error=''){gate().innerHTML=`<div class="dr-shell"><div class="dr-brand">DRAGON GAMES · ${esc(TITLE)}</div><div class="dr-card"><h1>${esc(TITLE)}</h1><p>Mestre abre a sala com Google. Os demais entram pelo código ou pelo QR.</p>${error?`<div class="dr-error">${esc(error)}</div>`:''}<button class="dr-btn" id="drOpen">Abrir uma mesa</button><button class="dr-btn secondary" id="drJoin">Entrar com código</button><button class="dr-btn secondary" id="drSolo">Ensaiar neste aparelho</button></div></div>`;document.getElementById('drOpen').onclick=abrir;document.getElementById('drJoin').onclick=()=>formEntrar('');document.getElementById('drSolo').onclick=()=>liberar({local:true});}
function formEntrar(err=''){gate().innerHTML=`<div class="dr-shell"><div class="dr-brand">${esc(TITLE)}</div><div class="dr-card"><h2>Entrar em uma mesa</h2><p>Digite o código exibido pelo Mestre.</p><input class="dr-input" id="drCode" maxlength="6" placeholder="CÓDIGO" value="${esc(code||q||'')}"><input class="dr-input" id="drName" maxlength="60" placeholder="Seu nome">${err?`<div class="dr-error">${esc(err)}</div>`:''}<button class="dr-btn" id="drEnter">Entrar</button><button class="dr-btn secondary" id="drBack">Voltar</button></div></div>`;document.getElementById('drBack').onclick=()=>menu();document.getElementById('drEnter').onclick=entrar;setTimeout(()=>document.getElementById('drName')?.focus(),20)}
async function google(){const provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});try{return (await signInWithPopup(auth,provider)).user}catch(e){if(['auth/popup-blocked','auth/operation-not-supported-in-this-environment'].includes(e.code)){sessionStorage.setItem('dragon.room.open','1');await signInWithRedirect(auth,provider);return null}throw e}}
async function abrir(){try{const u=await google();if(!u)return;code=gerar();for(let i=0;i<8;i++){if(!(await getDoc(roomRef(code))).exists())break;code=gerar()}await setDoc(roomRef(code),{ativa:true,fase:'sala',mestreUid:u.uid,criadaEm:serverTimestamp(),criadaEmMs:Date.now(),modo:'multiplayer'});await setDoc(playerRef(code,u.uid),{nome:(u.displayName||'Mestre').slice(0,60),mestre:true,entrouMs:Date.now()});role='master';ouvir();renderLobby()}catch(e){menu(e?.message||'Não foi possível criar a mesa.')}}
async function entrar(){try{code=(document.getElementById('drCode').value||'').trim().toUpperCase();const nome=(document.getElementById('drName').value||'').trim();if(code.length!==6||!nome)return formEntrar('Informe o código e seu nome.');const snap=await getDoc(roomRef(code));if(!snap.exists()||snap.data().ativa!==true)return formEntrar('Sala não encontrada ou encerrada.');let u=auth.currentUser;if(!u||!u.isAnonymous)u=(await signInAnonymously(auth)).user;await setDoc(playerRef(code,u.uid),{nome:nome.slice(0,60),mestre:false,entrouMs:Date.now()},{merge:true});role='guest';ouvir();renderLobby()}catch(e){formEntrar(e?.message||'Não foi possível entrar.')}}
function ouvir(){unsubRoom?.();unsubPlayers?.();unsubRoom=onSnapshot(roomRef(code),s=>{room=s.exists()?s.data():null;if(room?.fase==='jogo')liberar({code,role,room});else renderLobby()});unsubPlayers=onSnapshot(collection(db,ROOT,code,'jogadores'),s=>{players=s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.entrouMs||0)-(b.entrouMs||0));renderLobby()})}
function renderLobby(){if(!code||!room)return;const master=role==='master';gate().innerHTML=`<div class="dr-shell"><div class="dr-brand">${esc(TITLE)} · ${master?'MESTRE DA MESA':'SALA'}</div><div class="dr-card"><h2>${master?'Sala aberta':'Você entrou'}</h2><div class="dr-code">${esc(code)}</div>${master?`<div class="dr-qr">${qr(code)}</div><p class="dr-note">Aponte os celulares para o QR ou use o código.</p>`:''}<div class="dr-list">${players.map(p=>`<div class="dr-player"><span>${esc(p.nome||'Jogador')}</span><b>${p.mestre?'Mestre':'conectado'}</b></div>`).join('')}</div>${master?`<button class="dr-btn" id="drStart" ${players.length<1?'disabled':''}>Iniciar partida</button>`:`<p class="dr-note">Aguardando o Mestre iniciar a partida…</p>`}</div></div>`;if(master)document.getElementById('drStart').onclick=async()=>{await updateDoc(roomRef(code),{fase:'jogo',iniciadaEmMs:Date.now()})}}
function liberar(detail){unsubRoom?.();unsubPlayers?.();document.getElementById('dragonRoomGate')?.remove();window.MOSAICO_ROOM=detail;window.dispatchEvent(new CustomEvent(READY_EVENT,{detail}))}
css();
getRedirectResult(auth).then(r=>{if(r?.user&&sessionStorage.getItem('dragon.room.open')){sessionStorage.removeItem('dragon.room.open');abrir()}else if(q){code=q.toUpperCase();formEntrar()}else menu()}).catch(()=>{if(q){code=q.toUpperCase();formEntrar()}else menu()});
