(function(){
'use strict';
let root=null,button=null,panel=null,unsubRoom=null,unsubPlayers=null,room=null,players=[];
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));}
function ensureStyle(){if(document.getElementById('mosaico-master-sala-style'))return;const st=document.createElement('style');st.id='mosaico-master-sala-style';st.textContent=`
#masterSalaPersistent{position:fixed;left:0;right:0;bottom:0;z-index:2147483000;padding:max(8px,env(safe-area-inset-bottom)) 10px 10px;pointer-events:none;background:linear-gradient(180deg,transparent,rgba(2,5,8,.92) 28%)}
#masterSalaPersistent .msp-btn{pointer-events:auto;width:100%;min-height:54px;border:1px solid #35556a;border-radius:12px;background:linear-gradient(180deg,#0d1d27,#07131b);color:#d6f3ff;font:800 13px Inter,system-ui,sans-serif;letter-spacing:.18em;text-transform:uppercase;box-shadow:inset 0 1px rgba(255,255,255,.08),0 5px 0 #010305,0 11px 20px rgba(0,0,0,.42);cursor:pointer;transform:translateY(0);transition:transform .1s ease,box-shadow .1s ease}
#masterSalaPersistent .msp-btn:active{transform:translateY(4px);box-shadow:inset 0 1px rgba(255,255,255,.03),0 1px 0 #010305}
#masterSalaPanel{position:fixed;inset:0;z-index:2147483001;background:rgba(1,4,7,.82);backdrop-filter:blur(5px);display:flex;justify-content:center;align-items:flex-start;overflow:auto;padding:28px 16px 90px}
#masterSalaPanel[hidden]{display:none}
#masterSalaPanel .msp-card{width:min(660px,100%);background:#071018;border:1px solid #315064;border-radius:14px;padding:18px;color:#e7eef4;box-shadow:inset 0 1px rgba(255,255,255,.05),0 6px 0 #020508,0 24px 70px rgba(0,0,0,.55)}
#masterSalaPanel .msp-head{display:flex;align-items:flex-start;justify-content:space-between;gap:14px;margin-bottom:12px}.msp-head h2{margin:4px 0 0;font:600 38px 'Cormorant Garamond',serif}.msp-kicker{font:800 11px Inter,sans-serif;letter-spacing:.22em;color:#8da7bb}.msp-close,.msp-action{min-height:46px;border:1px solid #38556a;border-radius:8px;background:linear-gradient(180deg,#10222d,#0b1720);color:#e7eef4;padding:10px 14px;font-weight:800;cursor:pointer;box-shadow:inset 0 1px rgba(255,255,255,.06),0 4px 0 #020407,0 8px 15px rgba(0,0,0,.3);transform:translateY(0);transition:transform .1s ease,box-shadow .1s ease}.msp-close:active,.msp-action:active{transform:translateY(3px);box-shadow:inset 0 1px rgba(255,255,255,.03),0 1px 0 #020407}.msp-action{width:100%;margin-top:10px}.msp-danger{border-color:#8d413b;color:#ffd0ca;background:linear-gradient(180deg,#361714,#25100e)}.msp-code{font:800 42px/1 ui-monospace,monospace;letter-spacing:.13em;text-align:center;color:#ffc269;padding:14px 0}.msp-qr{width:min(260px,78vw);margin:0 auto;background:#fff;border-radius:10px;padding:10px;box-shadow:0 5px 0 #4d391f,0 12px 24px rgba(0,0,0,.36)}.msp-qr svg{display:block;width:100%;height:auto}.msp-section{border-top:1px solid #263846;margin-top:16px;padding-top:14px}.msp-section h3{font:700 14px Inter,sans-serif;letter-spacing:.08em;text-transform:uppercase;color:#9fb4c3;margin:0 0 9px}.msp-player{display:flex;justify-content:space-between;gap:12px;padding:9px 0;border-bottom:1px solid #172631}.msp-muted{color:#8ba0af}.msp-status{padding:10px 12px;border:1px solid #284153;border-radius:8px;background:#08131a;color:#b9ccd8}
`;document.head.appendChild(st)}
function joinUrl(code){const u=new URL(location.href);u.search='';u.searchParams.set('sala',code);return u.toString();}
function qr(code){try{return window.MosaicoQR?window.MosaicoQR.svg(joinUrl(code),{nivel:'M',margem:2,rotulo:'QR da sala',fundo:'#ffffff',tinta:'#05070c'}):''}catch(e){return ''}}
function renderPanel(){if(!panel||!window.MosaicoSala)return;const s=window.MosaicoSala,code=s.roomCode||'';const fase=(room&&room.fase)||'—';const list=players.map(p=>`<div class="msp-player"><span>${esc(p.nome||'Jogador')}</span><span class="msp-muted">${p.mestre?'Mestre':(p.pronto?'pronto':'conectado')}</span></div>`).join('')||'<div class="msp-muted">Nenhum participante.</div>';panel.innerHTML=`<div class="msp-card"><div class="msp-head"><div><div class="msp-kicker">MESTRE · ${esc(fase)}</div><h2>Sala</h2></div><button class="msp-close" id="mspClose">Fechar</button></div><div class="msp-status">A Sala permanece disponível durante toda a partida.</div><div class="msp-section"><h3>Código e QR da sala</h3><div class="msp-code">${esc(code)}</div><div class="msp-qr">${qr(code)}</div></div><div class="msp-section"><h3>Participantes · ${players.length}</h3>${list}</div><div class="msp-section"><h3>Controle da sala</h3><button class="msp-action msp-danger" id="mspEnd">Encerrar sala</button></div></div>`;panel.querySelector('#mspClose').onclick=()=>panel.hidden=true;panel.querySelector('#mspEnd').onclick=encerrar;}
async function encerrar(){const s=window.MosaicoSala;if(!s||s.role!=='master'||!s.db||!s.roomCode)return;if(!confirm('Encerrar esta sala para todos os participantes?'))return;try{await s.db.collection('noite').doc(s.roomCode).update({ativa:false,encerradaEmMs:Date.now()});panel.hidden=true;location.href=location.pathname;}catch(e){alert('Não foi possível encerrar a sala: '+(e&&e.message?e.message:e));}}
function ensureUi(){const s=window.MosaicoSala;if(!s||s.role!=='master'||!s.db||!s.roomCode)return false;ensureStyle();if(!document.getElementById('masterSalaPersistent')){root=document.createElement('div');root.id='masterSalaPersistent';root.innerHTML='<button class="msp-btn" type="button">Sala</button>';document.body.appendChild(root);}else root=document.getElementById('masterSalaPersistent');button=root.querySelector('.msp-btn');if(!document.getElementById('masterSalaPanel')){panel=document.createElement('div');panel.id='masterSalaPanel';panel.hidden=true;document.body.appendChild(panel);}else panel=document.getElementById('masterSalaPanel');button.onclick=()=>{panel.hidden=!panel.hidden;if(!panel.hidden)renderPanel();};return true;}
function attach(){const s=window.MosaicoSala;if(!ensureUi())return false;const ref=s.db.collection('noite').doc(s.roomCode);if(unsubRoom)unsubRoom();if(unsubPlayers)unsubPlayers();unsubRoom=ref.onSnapshot(x=>{room=x.exists?x.data():null;if(room&&room.ativa===false){root?.remove();panel?.remove();return}ensureUi();if(panel&&!panel.hidden)renderPanel();});unsubPlayers=ref.collection('jogadores').orderBy('entrouMs').onSnapshot(x=>{players=x.docs.map(d=>({id:d.id,...d.data()}));ensureUi();if(panel&&!panel.hidden)renderPanel();});return true;}
let tries=0;const timer=setInterval(()=>{tries++;if(attach()||tries>120)clearInterval(timer);},250);
const keeper=setInterval(()=>{if(window.MosaicoSala?.role==='master')ensureUi();},500);
window.addEventListener('beforeunload',()=>{clearInterval(keeper);if(unsubRoom)unsubRoom();if(unsubPlayers)unsubPlayers();});
})();