(function(){
'use strict';
const CFG={apiKey:'AIzaSyA160bkgHBrYBwvIxlENax-aAyLWPMaOU4',authDomain:'mosaico-noite.firebaseapp.com',projectId:'mosaico-noite',storageBucket:'mosaico-noite.firebasestorage.app',messagingSenderId:'703343424116',appId:'1:703343424116:web:e6990b5c00d43aca6e9721'};
const ORDEM=['sete','cinco','apagao','nome','corpo','perceber'];
const ROT='mosaico_casa_ultima_partida_noite';
const root=document.getElementById('app');
let app,auth,db,roomCode='',roomData=null,players=[],unsubRoom=null,unsubPlayers=null,role='';
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function init(){ if(!firebase.apps.length) app=firebase.initializeApp(CFG,'noite-shell'); else app=firebase.apps[0]; auth=firebase.auth(app); db=firebase.firestore(app); renderMenu(); const q=new URLSearchParams(location.search).get('sala'); if(q){roomCode=q.toUpperCase();renderJoin();} }
function nextPartida(){let last='';try{last=localStorage.getItem(ROT)||''}catch(e){}let i=ORDEM.indexOf(last);return ORDEM[(i+1+ORDEM.length)%ORDEM.length]||'sete';}
function markPartida(id){try{localStorage.setItem(ROT,id)}catch(e){}}
function code(){const A='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';let s='';for(let i=0;i<6;i++)s+=A[Math.floor(Math.random()*A.length)];return s;}
function base(title,body){root.innerHTML=`<main class="stage shell"><section class="dossie"><span class="eyebrow">MOSAICO · A NOITE</span><h2>${title}</h2>${body}</section></main>`;}
function renderMenu(){base('A Casa da Costa',`<p class="lead">Uma mesa multiplayer. O Mestre abre a sala; os demais entram pelo QR ou pelo código.</p><div class="toolbar"><button class="btn btn-gold" id="open">Abrir uma mesa</button><button class="btn btn-ghost" id="join">Entrar com código</button><button class="btn btn-ghost" id="solo">Ensaiar sozinho</button></div>`);document.getElementById('open').onclick=renderCreate;document.getElementById('join').onclick=renderJoin;document.getElementById('solo').onclick=launchLocal;}
function renderCreate(){base('Abrir uma mesa',`<p class="lead">O Mestre entra com Google. A pergunta da sessão é atribuída automaticamente pelo MOSAICO.</p><div class="campo"><label>Seu nome</label><input id="name" class="room-input" maxlength="60" placeholder="Nome do Mestre"></div><div class="toolbar"><button class="btn btn-gold" id="google">Continuar com Google</button><button class="btn btn-ghost" id="back">Voltar</button></div><p id="err" class="muted"></p>`);document.getElementById('google').onclick=createRoom;document.getElementById('back').onclick=renderMenu;}
function renderJoin(){base('Entrar em uma mesa',`<p class="lead">Use o código exibido pelo Mestre ou abra diretamente pelo QR.</p><div class="campo"><label>Código</label><input id="code" class="room-input" maxlength="6" value="${esc(roomCode)}" placeholder="ABC123" style="text-transform:uppercase"></div><div class="campo"><label>Seu nome</label><input id="name" class="room-input" maxlength="60" placeholder="Seu nome"></div><div class="toolbar"><button class="btn btn-gold" id="enter">Entrar</button><button class="btn btn-ghost" id="back">Voltar</button></div><p id="err" class="muted"></p>`);document.getElementById('enter').onclick=joinRoom;document.getElementById('back').onclick=renderMenu;}
async function createRoom(){const name=(document.getElementById('name').value||'Mestre').trim();const err=document.getElementById('err');err.textContent='Entrando com Google…';try{const provider=new firebase.auth.GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});const cred=await auth.signInWithPopup(provider);let c=code();for(let i=0;i<8;i++){const s=await db.collection('noite').doc(c).get();if(!s.exists)break;c=code();}const partidaId=nextPartida();await db.collection('noite').doc(c).set({ativa:true,fase:'sala',vez:0,modo:'com-telao',ritmo:'automatico',mestreUid:cred.user.uid,criadaEm:firebase.firestore.FieldValue.serverTimestamp(),criadaEmMs:Date.now(),formato:'cheia',v3:true,partidaId});await db.collection('noite').doc(c).collection('jogadores').doc(cred.user.uid).set({nome:name||'Mestre',personagem:'',forma:'n',pronto:true,entrouMs:Date.now(),votos:0,moedas:9,total:0,atualizadoEmMs:Date.now()});markPartida(partidaId);role='master';roomCode=c;listen();}catch(e){err.textContent='Não foi possível criar a mesa. '+(e&&e.message?e.message:e);}}
async function joinRoom(){const c=(document.getElementById('code').value||'').trim().toUpperCase(),name=(document.getElementById('name').value||'Jogador').trim(),err=document.getElementById('err');if(c.length!==6){err.textContent='Informe o código de 6 caracteres.';return;}try{let user=auth.currentUser;if(!user||!user.isAnonymous){if(user)await auth.signOut();user=(await auth.signInAnonymously()).user;}const ref=db.collection('noite').doc(c),snap=await ref.get();if(!snap.exists||snap.data().ativa!==true)throw new Error('Sala não encontrada ou encerrada.');await ref.collection('jogadores').doc(user.uid).set({nome:name||'Jogador',personagem:'',forma:'n',pronto:true,entrouMs:Date.now(),votos:0,moedas:9,total:0,atualizadoEmMs:Date.now()},{merge:true});role='guest';roomCode=c;listen();}catch(e){err.textContent='Não foi possível entrar. '+(e&&e.message?e.message:e);}}
function listen(){if(unsubRoom)unsubRoom();if(unsubPlayers)unsubPlayers();const ref=db.collection('noite').doc(roomCode);unsubRoom=ref.onSnapshot(s=>{roomData=s.exists?s.data():null;if(!roomData){renderMenu();return;}if(roomData.fase==='sala')renderLobby();else launchOnline();});unsubPlayers=ref.collection('jogadores').orderBy('entrouMs').onSnapshot(s=>{players=s.docs.map(d=>({id:d.id,...d.data()}));if(roomData&&roomData.fase==='sala')renderLobby();});}
function renderLobby(){if(!roomData)return;const url=location.origin+location.pathname+'?sala='+encodeURIComponent(roomCode);const qr=window.MosaicoQR?MosaicoQR.svg(url,{nivel:'M',margem:4,rotulo:'QR para entrar na Noite'}):'';const names=players.map(p=>`<span class="chip">${esc(p.nome)}</span>`).join('');base('Sala aberta',`<div class="question"><b>Código da sala</b><p style="font-size:2.7rem;letter-spacing:.15em">${roomCode}</p></div><div class="room-grid"><div class="room-qr">${qr}</div><div><p class="muted">Aponte a câmera para o QR ou informe o código.</p><div class="statusline">${names||'<span class="chip">Aguardando jogadores…</span>'}</div><p class="muted">${players.length} participante(s)</p></div></div>${role==='master'?'<button class="btn btn-gold" id="start">Iniciar A Noite</button>':'<div class="quote">Aguarde o Mestre iniciar a sessão.</div>'}`);if(role==='master')document.getElementById('start').onclick=async()=>{await db.collection('noite').doc(roomCode).update({fase:'dossie',iniciadaEmMs:Date.now()});};}
function launchOnline(){if(window.__MOSAICO_NOITE_LAUNCHED)return;window.__MOSAICO_NOITE_LAUNCHED=true;window.MosaicoSala={online:true,role,roomCode,roomData,players,auth,db};const id=roomData.partidaId||'sete';const idx=ORDEM.indexOf(id);try{localStorage.setItem(ROT,ORDEM[(idx-1+ORDEM.length)%ORDEM.length]);localStorage.removeItem('mosaico_noite_costa_auto');}catch(e){}root.innerHTML='';const s=document.createElement('script');s.src='noite-auto.js?v=20260830-room';document.body.appendChild(s);}
function launchLocal(){window.__MOSAICO_NOITE_LAUNCHED=true;root.innerHTML='';const s=document.createElement('script');s.src='noite-auto.js?v=20260830-room';document.body.appendChild(s);}
window.addEventListener('beforeunload',()=>{if(unsubRoom)unsubRoom();if(unsubPlayers)unsubPlayers();});
init();
})();