const PARTIDAS={
  peso:{title:'O Peso do Malote 41',nature:'QUANTO + QUANDO',question:'O banco anuncia que faltam quatrocentos e oitenta mil reais. Quanto realmente desapareceu?',short:'Um número parece óbvio. A direção do dinheiro não.',activities:['vidro','escura'],fields:[
    ['Valor declarado',['R$ 480.000','R$ 384.000','R$ 96.000','R$ 0'],'R$ 480.000'],
    ['Valor físico antes da manhã',['R$ 480.000','R$ 384.000','R$ 96.000','R$ 0'],'R$ 384.000'],
    ['Movimento líquido da manhã',['+ R$ 96.000','− R$ 96.000','− R$ 480.000','R$ 0'],'+ R$ 96.000'],
    ['Diferença física real às 8h40',['R$ 480.000','R$ 384.000','R$ 96.000','R$ 0'],'R$ 0'],
    ['Quando nasceu a diferença?',['Na janela de 87 s','Às 8h02','Na véspera','Onze dias antes'],'Onze dias antes']],
    answer:'Naquela manhã, R$ 0 desapareceram fisicamente. A diferença de R$ 96.000 nasceu onze dias antes como duplicidade escritural.',
    reveals:['O saco no chão pesa 0,4 kg. O malote coletado pesa 5,1 kg.','Às 8h40 a tesouraria confere R$ 480.000 íntegros.','A janela de 87 segundos foi usada para inserir R$ 96.000.','Um depósito de R$ 96.000 foi lançado duas vezes onze dias antes.']},
  janela:{title:'Os 87 Segundos',nature:'O QUÊ + COMO',question:'O que realmente aconteceu enquanto a câmera 3 ficou cega?',short:'Reconstrua a janela sem pressupor retirada.',activities:['norte','escura','vidro'],fields:[
    ['Primeiro evento',['Rádio afasta Vigilância','Lacre é rompido','Malote sai da agência','Etiqueta é impressa'],'Rádio afasta Vigilância'],
    ['O que ocorre no malote?',['R$ 480.000 saem','R$ 96.000 entram','Nada é tocado','O malote é trocado'],'R$ 96.000 entram'],
    ['O que ocorre com o lacre?',['Permanece ML-8842','É trocado por ML-8847','Desaparece','É rompido só no destino'],'É trocado por ML-8847'],
    ['Direção do fluxo',['Agência → rua','Malote → corredor','Fora → dentro do malote','Tesouraria → agência'],'Fora → dentro do malote'],
    ['Fim da janela',['7h58min12s','7h58min50s','7h59min39s','8h02'],'7h59min39s']],
    answer:'Durante os 87 segundos, a vigilância foi afastada, o lacre foi rompido, R$ 96.000 foram inseridos no malote, um novo lacre foi aplicado e o malote voltou à custódia.',
    reveals:['A câmera cai às 7h58min12s.','O lacre é rompido e R$ 96.000 entram.','ML-8847 substitui ML-8842.','A câmera retorna às 7h59min39s.']},
  roubo:{title:'Foi um roubo?',nature:'QUAL / QUE TIPO',question:'Todo mundo viu os sinais de um assalto. Mas houve realmente um roubo?',short:'Classifique o acontecimento sem confundir irregularidade com subtração.',activities:['vidro','escura'],fields:[
    ['Natureza da manhã',['Roubo consumado','Tentativa de roubo','Bagunça administrativa sem ação deliberada','Encenação operacional de reparação clandestina'],'Encenação operacional de reparação clandestina'],
    ['Houve subtração de valores?',['Sim, R$ 480.000','Sim, R$ 96.000','Não','Não é possível saber'],'Não'],
    ['A falha da câmera foi',['Acidental','Deliberadamente preparada','Rotina técnica','Produzida pela transportadora'],'Deliberadamente preparada'],
    ['A diferença central é',['Patrimonial','Escritural','De transporte','De lacre'],'Escritural'],
    ['A leitura “só bagunça” é',['Totalmente correta','Parcialmente correta','Totalmente falsa','Irrelevante'],'Parcialmente correta']],
    answer:'Não houve roubo naquela manhã. Houve uma encenação operacional deliberada para reparar clandestinamente uma diferença escritural anterior.',
    reveals:['Os sinais de crime são reais.','A preparação da câmera e do acesso foi deliberada.','Nenhum dinheiro foi subtraído.','A irregularidade é grave, mas não é furto.']},
  antes:{title:'Antes das 8h02',nature:'QUANDO',question:'Quando nasceu a diferença que todos procuram?',short:'A mesa olha para minutos; a resposta está onze dias atrás.',activities:['norte'],fields:[
    ['Âncora da manhã',['7h47','7h58min12s','8h02','8h40'],'7h47'],
    ['Janela crítica',['87 segundos','3 minutos','11 dias','40 minutos'],'87 segundos'],
    ['Momento da duplicidade',['Na manhã','Na véspera','Onze dias antes','No destino'],'Onze dias antes'],
    ['Evento que transforma o erro em ameaça',['Chegada do carro-forte','Auditoria anunciada na véspera','Grito às 8h02','Reset da câmera'],'Auditoria anunciada na véspera'],
    ['A diferença física nasce',['Às 7h58','Às 8h02','Onze dias antes','Nunca nasce'],'Nunca nasce']],
    answer:'A diferença nasce onze dias antes, quando um depósito de R$ 96.000 é reconsolidado e lançado pela segunda vez. A manhã apenas tenta dar corpo ao número.',
    reveals:['7h47 ancora a manhã, não a origem.','Os 87 segundos explicam uma operação, não a criação da diferença.','A auditoria torna o erro antigo urgente.','O nascimento factual está no D-11.']},
  quem:{title:'Quem construiu a janela?',nature:'QUEM COMPOSTO',question:'Quem colocou cada peça daqueles 87 segundos em movimento?',short:'Separe decisão, preparação, execução, participação sem conhecimento e negligência.',activities:['norte','escura'],fields:[
    ['Quem decide a operação?',['Subgerente','Limpeza','Manutenção','Gerência'],'Subgerente'],
    ['Quem prepara a falha?',['Subgerente','Manutenção','Vigilância','Transporte'],'Subgerente'],
    ['Quem abre o acesso sem conhecer a finalidade?',['Limpeza','Aprendiz','Gerência','Cliente'],'Limpeza'],
    ['Quem executa o reset autorizado?',['Manutenção','Subgerente','Gerência','Vigilância'],'Manutenção'],
    ['Quem autoriza o reset sem contingência?',['Gerência','Manutenção','Transporte','Caixa Sênior'],'Gerência']],
    answer:'Subgerente decide e constrói a janela; Limpeza abre o acesso sem conhecer a finalidade; Manutenção executa um reset autorizado; Gerência autoriza sem contingência.',
    reveals:['Presença não é autoria.','Execução técnica não é decisão.','Abrir a porta não prova conhecimento da finalidade.','A cadeia é distribuída, mas a coordenação é identificável.']},
  proteger:{title:'O que estava sendo protegido?',nature:'POR QUÊ',question:'Se não era o dinheiro, o que alguém estava tentando salvar?',short:'A ação material contradiz o motivo aparente.',activities:['vidro'],fields:[
    ['O que Subgerente teme perder?',['R$ 480.000','A assinatura e a carreira','O malote 41','A chave 17-B'],'A assinatura e a carreira'],
    ['Por que usar dinheiro próprio?',['Para lavar produto de crime','Para completar fisicamente o saldo','Para pagar Transporte','Para comprar silêncio'],'Para completar fisicamente o saldo'],
    ['O que dispara a urgência?',['A garoa','A auditoria integral','O Cliente','O relógio da farmácia'],'A auditoria integral'],
    ['Qual ato original precisa ser escondido?',['Roubo anterior','Assinatura sem conferência física','Erro da transportadora','Abertura do cofre pelo Cliente'],'Assinatura sem conferência física'],
    ['O objetivo final é',['Enriquecimento','Desviar a auditoria para inocentes','Fazer registros e dinheiro coincidirem','Fechar a agência'],'Fazer registros e dinheiro coincidirem']],
    answer:'O objeto protegido era a assinatura — e, por extensão, a carreira. O dinheiro próprio foi usado para fazer a realidade física coincidir com um registro errado.',
    reveals:['R$ 96.000 saem da conta pessoal de Subgerente.','O dinheiro entra, não sai.','A auditoria ameaça revelar uma assinatura sem conferência.','A operação tenta salvar reputação, não patrimônio.']}
};

const SENSORS={
 norte:{title:'A Janela do Norte',desc:'Oriente o aparelho pelos setores da agência e fixe horários e posições.',href:'janela-do-norte.html'},
 vidro:{title:'O Vidro Embaçado',desc:'Limpe camadas de informação para revelar peso, lacres, valores e registros.',href:'vidro-embacado.html'},
 escura:{title:'A Sala às Escuras',desc:'Procure no corredor objetos físicos da zona cega sem transformá-los automaticamente em culpa.',href:'sala-as-escuras.html'}
};

const EVIDENCES=[
 ['F1','Antecipação interna','Terminal registra pedido de rota alternativa às 6h52.'],
 ['F2','Âncora 7h47','Recibo e registros eletrônicos fixam a chegada às 7h47.'],
 ['F5','Zona cega','A câmera 3 fica fora entre 7h58min12s e 7h59min39s.'],
 ['F7','Duas etiquetas','ML-8842 aparece rompido; ML-8847 foi impresso às 7h53.'],
 ['F8','Saco vazio','O saco no chão pesa 0,4 kg.'],
 ['F9','O peso','O malote entregue à custódia pesa 5,1 kg.'],
 ['F10','Destino','Às 8h40 a tesouraria confere R$ 480.000 íntegros.'],
 ['F11','Saque','Às 6h20 Subgerente saca R$ 96.000 de origem pessoal.'],
 ['F13','Duplicidade','O mesmo depósito de R$ 96.000 aparece duas vezes na consolidação D-11.'],
 ['F14','Assinatura','A consolidação D-11 foi assinada sem abertura física do cofre.'],
 ['F15','Auditoria','Às 21h47 da véspera chega convocação para contagem física integral.'],
 ['F16','Trajeto','Marcas e sensor ligam mesa, arquivos e retorno à custódia.']
];

const state={screen:'intro',game:null,players:6,pace:'pressure',selected:new Set(),sensorDone:new Set(),hypothesis:{},final:{},reveal:0,start:Date.now()};
const screens=[...document.querySelectorAll('.screen')];
function go(name){screens.forEach(s=>s.classList.toggle('active',s.dataset.screen===name));state.screen=name;document.getElementById('phaseLabel').textContent=({intro:'PRÓLOGO',games:'PARTIDAS',briefing:'PERGUNTA',sensory:'SENSORES',evidence:'FRAGMENTOS',hypothesis:'HIPÓTESE',mosaic:'RELAÇÕES',final:'DECISÃO',reveal:'REVELAÇÃO',score:'PLACAR'})[name]||name.toUpperCase();scrollTo(0,0)}
function optionList(opts,value=''){return `<option value="">Selecione…</option>${opts.map(o=>`<option ${o===value?'selected':''}>${o}</option>`).join('')}`}
function renderGames(){const host=document.getElementById('gameCards');host.innerHTML=Object.entries(PARTIDAS).map(([id,g])=>`<button class="game-card" data-game="${id}" type="button"><small>${g.nature}</small><h3>${g.title}</h3><p>${g.question}</p><b>${g.short}</b></button>`).join('');host.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>selectGame(b.dataset.game))}
function selectGame(id){state.game=id;state.selected.clear();state.sensorDone.clear();state.hypothesis={};state.final={};state.reveal=0;const g=PARTIDAS[id];document.getElementById('gameNature').textContent=g.nature;document.getElementById('gameTitle').textContent=g.title;document.getElementById('gameQuestion').textContent=g.question;document.getElementById('activityPlan').innerHTML=g.activities.map(a=>`<span class="activity-chip"><strong>${SENSORS[a].title}</strong> · ${SENSORS[a].desc}</span>`).join('');go('briefing')}
function renderSensors(){const g=PARTIDAS[state.game],host=document.getElementById('sensoryCards');host.innerHTML=g.activities.map(id=>{const s=SENSORS[id],done=state.sensorDone.has(id)||localStorage.getItem(`mosaico-cf-${id}`)==='done';if(done)state.sensorDone.add(id);return `<article class="sensor-card ${done?'done':''}" data-sensor="${id}"><small>ATIVIDADE SENSORIAL</small><h3>${s.title}</h3><p>${s.desc}</p><div class="sensor-actions"><a class="primary" href="${s.href}?partida=${state.game}&ritmo=${state.pace}">Abrir atividade</a><button class="ghost mark-sensor" type="button">${done?'Concluída ✓':'Marcar concluída'}</button></div></article>`}).join('');host.querySelectorAll('.mark-sensor').forEach(btn=>btn.onclick=()=>{const id=btn.closest('[data-sensor]').dataset.sensor;state.sensorDone.add(id);localStorage.setItem(`mosaico-cf-${id}`,'done');renderSensors()});renderSensorArchive()}
function renderSensorArchive(){const n=state.sensorDone.size;document.getElementById('sensorDone').textContent=`${n} atividade${n===1?'':'s'} concluída${n===1?'':'s'}`;document.getElementById('sensorTags').innerHTML=[...state.sensorDone].map(id=>`<span class="tag">${SENSORS[id].title}</span>`).join('')}
function renderEvidence(){const host=document.getElementById('evidenceGrid');host.innerHTML=EVIDENCES.map(([id,t,p])=>`<button class="evidence-card ${state.selected.has(id)?'selected':''}" data-e="${id}" type="button"><small>${id}</small><h3>${t}</h3><p>${p}</p></button>`).join('');host.querySelectorAll('[data-e]').forEach(b=>b.onclick=()=>{const id=b.dataset.e;state.selected.has(id)?state.selected.delete(id):state.selected.add(id);renderEvidence()})}
function renderHypothesis(){const g=PARTIDAS[state.game];document.getElementById('hypothesisPrompt').textContent=g.question;const f=g.fields.slice(0,2);document.getElementById('hypothesisForm').innerHTML=f.map(([label,opts])=>`<label><span>${label}</span><select name="${label}" required>${optionList(opts)}</select></label>`).join('')+`<button class="primary" type="submit">Fechar hipótese provisória</button>`}
function renderRelations(){const g=PARTIDAS[state.game];const rels={peso:['Saco vazio ↔ peso do malote','Peso ↔ conferência de destino','Saque ↔ janela de 87 s','Duplicidade ↔ auditoria'],janela:['Rádio ↔ início da zona cega','Saque ↔ lacre rompido','Etiqueta nova ↔ retorno do malote','Peso ↔ direção do fluxo'],roubo:['Irregularidade ↔ ausência de subtração','Saco vazio ↔ malote íntegro','Falha preparada ↔ finalidade não patrimonial','Erro administrativo ↔ encenação'],antes:['7h47 ↔ coleta','87 s ↔ operação','D-11 ↔ duplicidade','D-1 ↔ urgência'],quem:['Decisão ↔ Subgerente','Acesso ↔ Limpeza','Reset ↔ Manutenção','Autorização ↔ Gerência'],proteger:['Saque pessoal ↔ reposição','Auditoria ↔ medo','Assinatura ↔ omissão','Dinheiro entrando ↔ finalidade']}[state.game];document.getElementById('relationGrid').innerHTML=rels.map((r,i)=>`<button class="relation-card" type="button"><small>R${i+1}</small><h3>${r}</h3><p>Use esta relação para testar sua hipótese; o fato continua o mesmo mesmo se a interpretação mudar.</p></button>`).join('');document.querySelectorAll('.relation-card').forEach(b=>b.onclick=()=>b.classList.toggle('selected'));document.getElementById('oldHypothesis').textContent=Object.values(state.hypothesis).filter(Boolean).join(' · ')||'Nenhuma hipótese registrada';document.getElementById('counterPrompt').textContent=`Qual relação enfraquece a leitura inicial de “${g.short}”?`}
function renderFinal(){const g=PARTIDAS[state.game];document.getElementById('finalPrompt').textContent=g.question;document.getElementById('finalForm').innerHTML=g.fields.map(([label,opts])=>`<label><span>${label}</span><select name="${label}" required>${optionList(opts)}</select></label>`).join('')+`<button class="primary" type="submit">Fechar decisão</button>`}
function scoreFinal(){const g=PARTIDAS[state.game];let correct=0;g.fields.forEach(([label,,ans])=>{if(state.final[label]===ans)correct++});const quality=Math.round(correct/g.fields.length*55),relations=Math.min(20,state.selected.size*3),sensory=Math.round(state.sensorDone.size/g.activities.length*15),commit=10;return {total:quality+relations+sensory+commit,quality,relations,sensory,commit,correct}}
function renderReveal(){const g=PARTIDAS[state.game],steps=[{k:'O QUE PARECIA',h:'R$ 480.000 desapareceram.',p:'Um saco vazio, câmera cega e vigilância afastada organizam a interpretação antes da conferência.'},...g.reveals.map((x,i)=>({k:`RELAÇÃO ${i+1}`,h:x,p:'Nenhum fato anterior foi alterado; mudou a relação entre as evidências.'})),{k:'INFERÊNCIA CANÔNICA',h:g.answer,p:'A realidade é a mesma em todas as partidas. Esta pergunta apenas exige outro corte dela.'}];const s=steps[Math.min(state.reveal,steps.length-1)];document.getElementById('revealStage').innerHTML=`<div><span class="kicker">${s.k}</span><h2>${s.h}</h2><p>${s.p}</p></div>`;document.getElementById('nextReveal').textContent=state.reveal>=steps.length-1?'Ver resultado →':'Continuar revelação →'}
function renderScore(){const g=PARTIDAS[state.game],s=scoreFinal();document.getElementById('scoreTitle').textContent=g.title;document.getElementById('totalScore').textContent=s.total;const rows=[['Qualidade da decisão',s.quality,55],['Relações construídas',s.relations,20],['Atividades sensoriais',s.sensory,15],['Compromisso com hipótese',s.commit,10]];document.getElementById('scoreBars').innerHTML=rows.map(([n,v,m])=>`<div class="score-row"><span>${n}</span><div class="bar"><i style="width:${v/m*100}%"></i></div><b>${v}</b></div>`).join('');document.getElementById('endingCards').innerHTML=`<article class="ending-card"><b>PERGUNTA</b><h3>${g.question}</h3><p>${g.answer}</p></article><article class="ending-card"><b>ACERTOS</b><h3>${s.correct}/${g.fields.length}</h3><p>Campos corretos da resolução específica desta partida.</p></article><article class="ending-card"><b>PRINCÍPIO</b><h3>Fato não é interpretação.</h3><p>Uma nova evidência pode reorganizar a leitura sem reescrever nenhum fato.</p></article>`}

document.getElementById('chooseGame').onclick=()=>{state.players=+document.getElementById('playerCount').value;state.pace=document.getElementById('pace').value;renderGames();go('games')};document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>go(b.dataset.back));document.getElementById('startGame').onclick=()=>{renderSensors();go('sensory')};document.getElementById('toEvidence').onclick=()=>{renderEvidence();go('evidence')};document.getElementById('toHypothesis').onclick=()=>{renderHypothesis();go('hypothesis')};document.getElementById('hypothesisForm').onsubmit=e=>{e.preventDefault();state.hypothesis=Object.fromEntries(new FormData(e.currentTarget));renderRelations();go('mosaic')};document.getElementById('toFinal').onclick=()=>{renderFinal();go('final')};document.getElementById('finalForm').onsubmit=e=>{e.preventDefault();state.final=Object.fromEntries(new FormData(e.currentTarget));state.reveal=0;renderReveal();go('reveal')};document.getElementById('nextReveal').onclick=()=>{const max=PARTIDAS[state.game].reveals.length+1;if(state.reveal>=max){renderScore();go('score')}else{state.reveal++;renderReveal()}};document.getElementById('playAgain').onclick=()=>{renderGames();go('games')};document.getElementById('resetBtn').onclick=()=>{if(confirm('Reiniciar a Mesa e voltar à escolha inicial?'))location.reload()};setInterval(()=>{const d=Math.floor((Date.now()-state.start)/1000),m=String(Math.floor(d/60)).padStart(2,'0'),s=String(d%60).padStart(2,'0');document.getElementById('timer').textContent=`${m}:${s}`},1000);
