const story=[
 'A garoa apagava as cores, menos os números no verso de um recibo.',
 'O relógio da farmácia insistia num horário que a rua já havia deixado para trás.',
 'No pulso do Técnico, duas palavras apareceram e desapareceram.',
 'Uma pasta azul abriu; metal girou sob o balcão.',
 'A voz no rádio parecia conhecida, mas o chiado guardou parte dela.',
 'A fechadura nova cedeu para uma mão que conhecia o encaixe.',
 'Quando a imagem voltou, havia uma etiqueta nova e um malote baixo demais.',
 'A frase “falta dinheiro” chegou antes da conferência.'
];
const terminalText='Um malote está no chão. A câmera 3 perdeu 87 segundos. O sistema insiste que nada foi registrado.';
function typeTerminal(){const el=document.getElementById('terminalLine');let i=0;el.textContent='';const write=()=>{if(i<terminalText.length){const step=Math.random()>.9?2:1;el.textContent=terminalText.slice(0,i+=step);setTimeout(write,22+Math.random()*34)}};setTimeout(write,420)}
typeTerminal();
const typedScreens=new Set();
document.querySelectorAll('.section-head>p').forEach(el=>{const text=el.getAttribute('aria-label')||el.textContent.trim();el.dataset.terminalText=text;el.classList.add('terminal-copy');el.textContent=''});
function typeScreenTerminal(name){if(typedScreens.has(name))return;const el=document.querySelector(`[data-screen="${name}"] .section-head>p`);if(!el)return;typedScreens.add(name);const text=el.dataset.terminalText||el.getAttribute('aria-label')||'';let i=0;el.textContent='';const write=()=>{if(i<text.length){el.textContent=text.slice(0,++i);setTimeout(write,24+Math.random()*28)}};setTimeout(write,220)}
const pieces=[
 {id:'F2-01',title:'O recibo',text:'7h47 está legível sob uma mancha de café. A borda procura o reflexo de um relógio.',pos:'0% 0%'},
 {id:'F2-02',title:'A rota',text:'A prancheta registra R-4. A entrada parece ter sido antecipada.',pos:'50% 0%'},
 {id:'F2-03',title:'Erro 17',text:'No pulso do Técnico, a captura termina antes do nome do remetente.',pos:'100% 0%'},
 {id:'F2-08',title:'A fechadura',text:'O reparo é recente. Alguém conhecia o estalo do novo encaixe.',pos:'0% 100%'},
 {id:'F2-09',title:'A voz',text:'“Fundos. Dois minutos.” O áudio carrega uma voz conhecida.',pos:'50% 100%'},
 {id:'F2-10',title:'A etiqueta',text:'Duas fibras, dois brilhos, dois destinos na mesma superfície.',pos:'100% 100%'}
];
const suspects=['Selecione…','Subgerente','Funcionário da Limpeza','Técnico de Manutenção','Caixa Veterano','Estagiária','Segurança Interno','Motorista do carro-forte','Cliente Desconhecido','Gerente'];
const motives=['Selecione…','Encobrir/desviar diferença da auditoria','Roubo oportunista','Erro humano','Golpe externo','Vingança pessoal'];
const actions=['Selecione…','Induzir reset + afastar Segurança + trocar/reetiquetar','Deslocar o malote por engano','Desligar a câmera para manutenção','Trocar a pasta azul','Alterar a rota do veículo'];
const evidence=['P01 + P02 · antecipação e 7h47','P03 + P07 · Erro 17 e fio preparado','P05 + P08 · chaveiro e porta','P09 + P06 · rádio e 87 segundos','P10 + P11 · etiqueta e percurso','P12 · pasta azul'];
const routes=[
 {id:'Relógio',items:['P02 fixa 7h47','P01 prova pedido interno','P06 fecha 87 segundos','P11 mostra deslocamento','P10 revela reetiqueta']},
 {id:'Acesso',items:['P12 localiza a queda','P05 identifica a chave','P08 liga Limpeza à porta','P11 traça o malote','P04 liga 17—B ao Subgerente']},
 {id:'Código 17—B',items:['P03 mostra convocação','P04 põe o código com o Subgerente','P09 prova o afastamento','P05 converte código em acesso','P06 encaixa a janela']}
];
const investigations=[
 {verb:'OBSERVAR',name:'Janela do Norte',brief:'Compare a rua com registros internos. Selecione duas peças que corrigem o relógio da farmácia.',clues:['Recibo 7h47','Farmácia 7h44','Chegada do veículo','Garoa na calçada'],correct:[0,1],reward:['P01','P02']},
 {verb:'DISCERNIR',name:'Sala Clara',brief:'A luz revela tudo e destaca nada. Entre reflexos e objetos semelhantes, selecione as três observações que formam uma rota física verificável até os arquivos.',clues:['Reflexo do chaveiro 17—B','Pasta azul sob o balcão','Fechadura com riscos recentes','Envelope com tinta azul','Sola úmida no corredor','Mancha vermelha do lacre'],correct:[0,2,4],reward:['P05','P08','P11']},
 {verb:'AUTENTICAR',name:'Rádio em Três Camadas',brief:'Separe voz, aparelho e horário. Selecione as camadas que ligam a ordem ao início dos 87 segundos.',clues:['Voz atribuída ao Subgerente','Mancha vermelha','Log do rádio reserva','Recibo da padaria'],correct:[0,2],reward:['P09','P06']}
];
const lots=[
 {type:'PILAR',name:'Lacre sob luz',cost:4,text:'Revela a borda de uma etiqueta sobreposta.',result:'P10 validado: havia duas etiquetas e dois destinos.'},
 {type:'CONECTOR',name:'Rastro de água',cost:3,text:'Liga posições antes e depois da câmera.',result:'P11 conectado: mesa → arquivos → chão.'},
 {type:'CONTEXTO',name:'Auditoria 17—B',cost:3,text:'Explica por que o código importava.',result:'Motivo validado: diferença ligada à auditoria.'},
 {type:'AMBIGUIDADE',name:'A pasta azul',cost:2,text:'Pode acusar ou inocentar a Estagiária.',result:'P12 corrige a rota: a troca da pasta foi acidental.'}
];
const perspectives=['Técnico','Caixa Veterano','Estagiária','Segurança Interno','Motorista','Cliente Desconhecido'];
const perspectiveImages=['assets/fragmento-tecnico.png','assets/fragmento-veterano.png','assets/fragmento-estagiaria.png','assets/fragmento-seguranca.png','assets/carro-forte-hero.png','assets/fragmento-cliente.png'];
const remittances=[{name:'ÂMBAR',symbol:'◷',cls:'amber'},{name:'ÂMBAR',symbol:'◷',cls:'amber'},{name:'VERDE-PETRÓLEO',symbol:'⚿',cls:'teal'},{name:'VERDE-PETRÓLEO',symbol:'⚿',cls:'teal'},{name:'VERMELHO-LACRE',symbol:'◇',cls:'red'},{name:'VERMELHO-LACRE',symbol:'◇',cls:'red'}];
const state={screen:'intro',players:6,current:0,joined:new Set(),round:0,roundDone:new Set(),archive:[],credits:12,bought:new Set(),hypothesis:{},route:null,axis:null,final:{},reveal:0,start:Date.now()};
const screens=[...document.querySelectorAll('.screen')];
function goto(name){screens.forEach(s=>s.classList.toggle('active',s.dataset.screen===name));state.screen=name;document.getElementById('phaseLabel').textContent=({intro:'PRÓLOGO',briefing:'FASE 0',pieces:'FASE 1',investigation:'INVESTIGAÇÃO',hypothesis:'HIPÓTESE I',market:'MERCADO',mosaic:'MOSAICO',final:'DEDUÇÃO',reveal:'REVELAÇÃO',score:'PLACAR'})[name];typeScreenTerminal(name);scrollTo(0,0)}
document.querySelectorAll('[data-next]').forEach(b=>b.onclick=()=>{if(b.dataset.next==='briefing')state.players=+document.getElementById('playerCount').value;goto(b.dataset.next);if(b.dataset.next==='pieces')renderPlayers()});
document.getElementById('storyFragments').innerHTML=story.map((x,i)=>`<article class="story-fragment"><b>FRAGMENTO 0${i+1}</b><p>${x}</p></article>`).join('');
function renderPlayers(){const tabs=document.getElementById('playerTabs');tabs.innerHTML=Array.from({length:state.players},(_,i)=>`<button class="player-tab ${i===state.current?'active':''}" data-i="${i}"><small>ARQUIVO ${String(i+1).padStart(2,'0')}</small><span>${perspectives[i%perspectives.length]}</span>${state.joined.has(i)?'<b>✓</b>':''}</button>`).join('');tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>{state.current=+b.dataset.i;renderPlayers()});renderPiece();renderMini()}
let puzzle=null,puzzleTick=null;
function renderPiece(){document.getElementById('perspectiveName').textContent=`PERSPECTIVA DISTRIBUÍDA · ${perspectives[state.current%6]}`;const wall=document.getElementById('remittanceWall');wall.className='remittance-wall hidden';if(state.joined.has(state.current)){showRemittance();return}startPuzzle()}
function showRemittance(){const r=remittances[state.current%6],wall=document.getElementById('remittanceWall');wall.className=`remittance-wall ${r.cls}`;wall.innerHTML=`<div><span>REMESSA ${r.name}</span><strong>${r.symbol}</strong><small>Encontre a outra custódia desta cor.</small></div>`;document.getElementById('puzzleStatus').textContent='Fragmento concluído · dupla liberada'}
function startPuzzle(){clearInterval(puzzleTick);const canvas=document.getElementById('puzzleCanvas'),ctx=canvas.getContext('2d'),img=new Image();const board={x:28,y:28,w:480,h:300},pw=120,ph=100;let selected=null,drag={x:0,y:0},lastTap=0,time=90;
  const ps=Array.from({length:12},(_,i)=>{const row=Math.floor(i/4),col=i%4;return{i,row,col,tx:board.x+col*pw+pw/2,ty:board.y+row*ph+ph/2,x:560+Math.random()*220,y:45+Math.random()*420,rot:[0,90,180,270][Math.floor(Math.random()*4)],snapped:false}});
  function path(p){const x=-pw/2,y=-ph/2,s=14;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+pw*.38,y);ctx.bezierCurveTo(x+pw*.38,y+s,x+pw*.62,y+s,x+pw*.62,y);ctx.lineTo(x+pw,y);ctx.lineTo(x+pw,y+ph*.38);ctx.bezierCurveTo(x+pw-s,y+ph*.38,x+pw-s,y+ph*.62,x+pw,y+ph*.62);ctx.lineTo(x+pw,y+ph);ctx.lineTo(x+pw*.62,y+ph);ctx.bezierCurveTo(x+pw*.62,y+ph-s,x+pw*.38,y+ph-s,x+pw*.38,y+ph);ctx.lineTo(x,y+ph);ctx.lineTo(x,y+ph*.62);ctx.bezierCurveTo(x+s,y+ph*.62,x+s,y+ph*.38,x,y+ph*.38);ctx.closePath()}
  function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.save();ctx.globalAlpha=.22;ctx.drawImage(img,board.x,board.y,board.w,board.h);ctx.restore();ctx.strokeStyle='#d4ad68';ctx.strokeRect(board.x,board.y,board.w,board.h);for(const p of ps){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.rot*Math.PI/180);path(p);ctx.save();ctx.clip();ctx.drawImage(img,-p.col*pw-pw/2,-p.row*ph-ph/2,board.w,board.h);ctx.restore();ctx.strokeStyle=p.snapped?'#9be0cf':'#d4ad68';ctx.lineWidth=p.snapped?2.5:1.2;ctx.stroke();ctx.restore()}}
  function point(e){const r=canvas.getBoundingClientRect();return{x:(e.clientX-r.left)*canvas.width/r.width,y:(e.clientY-r.top)*canvas.height/r.height}}
  function pick(q){return [...ps].reverse().find(p=>!p.snapped&&Math.abs(q.x-p.x)<pw*.58&&Math.abs(q.y-p.y)<ph*.62)}
  function rotate(p){if(!p||p.snapped)return;p.rot=(p.rot+90)%360;draw();trySnap(p)}
  function trySnap(p){if(Math.hypot(p.x-p.tx,p.y-p.ty)<42&&p.rot%360===0){p.x=p.tx;p.y=p.ty;p.snapped=true;selected=null;draw();const done=ps.filter(x=>x.snapped).length;document.getElementById('puzzleStatus').textContent=`${done}/12 peças encaixadas`;if(done===12)complete()}}
  function complete(){clearInterval(puzzleTick);state.joined.add(state.current);renderMini();renderPlayers();showRemittance()}
  canvas.onpointerdown=e=>{const q=point(e),p=pick(q);if(!p)return;const now=Date.now();if(now-lastTap<320){rotate(p);lastTap=0;return}lastTap=now;selected=p;drag={x:q.x-p.x,y:q.y-p.y};ps.splice(ps.indexOf(p),1);ps.push(p);canvas.setPointerCapture(e.pointerId)};
  canvas.onpointermove=e=>{if(!selected)return;const q=point(e);selected.x=q.x-drag.x;selected.y=q.y-drag.y;draw()};canvas.onpointerup=e=>{if(selected)trySnap(selected);selected=null};canvas.oncontextmenu=e=>{e.preventDefault();rotate(pick(point(e)))};
  document.onkeydown=e=>{if(e.key.toLowerCase()==='r')rotate(selected)};document.getElementById('shufflePuzzle').onclick=()=>startPuzzle();img.onload=draw;img.src=perspectiveImages[state.current%perspectiveImages.length];puzzle={ps,draw};
  const timer=document.getElementById('puzzleTimer'),bar=document.getElementById('pressureBar');timer.textContent='01:30';bar.style.width='100%';puzzleTick=setInterval(()=>{time--;timer.textContent=`${String(Math.floor(time/60)).padStart(2,'0')}:${String(time%60).padStart(2,'0')}`;bar.style.width=`${time/90*100}%`;bar.style.background=time<=15?'#b96d61':'#66b7a5';if(time<=0){clearInterval(puzzleTick);document.getElementById('puzzleStatus').textContent='Tempo encerrado · embaralhe para tentar novamente'}},1000)}
function renderMini(){document.getElementById('mosaicMini').innerHTML=Array.from({length:6},(_,i)=>`<i class="mini-piece ${state.joined.has(i)?'filled':''}"></i>`).join('');document.getElementById('mosaicCount').textContent=`${state.joined.size} / ${state.players} peças`;document.getElementById('toInvestigation').disabled=state.joined.size<state.players}
document.getElementById('toInvestigation').onclick=()=>{clearInterval(puzzleTick);renderInvestigation();goto('investigation')};
function renderInvestigation(){document.getElementById('roundList').innerHTML=investigations.map((r,i)=>`<button class="round-button ${i===state.round?'active':''} ${state.roundDone.has(i)?'done':''}" data-round="${i}"><span>${r.verb}</span><b>${r.name}</b></button>`).join('');document.querySelectorAll('.round-button').forEach(b=>b.onclick=()=>{state.round=+b.dataset.round;renderInvestigation()});const r=investigations[state.round];document.getElementById('activityPanel').classList.toggle('bright-room',r.name==='Sala Clara');document.getElementById('activityPanel').innerHTML=`<span class="eyebrow">${r.verb}</span><h3>${r.name}</h3><p>${r.brief}</p><div class="activity-board">${r.clues.map((c,i)=>`<button class="clue-button" data-clue="${i}"><small>DETALHE ${i+1}</small>${c}</button>`).join('')}</div><button class="primary" id="validateRound">Validar cruzamento</button><div class="status" id="roundStatus">Selecione ${r.correct.length} observações.</div>`;let picks=[];document.querySelectorAll('.clue-button').forEach(b=>b.onclick=()=>{const n=+b.dataset.clue;if(picks.includes(n))picks=picks.filter(x=>x!==n);else if(picks.length<r.correct.length)picks.push(n);document.querySelectorAll('.clue-button').forEach(x=>x.classList.toggle('selected',picks.includes(+x.dataset.clue)))});document.getElementById('validateRound').onclick=()=>{const ok=r.correct.every(x=>picks.includes(x))&&picks.length===r.correct.length;document.getElementById('roundStatus').textContent=ok?'Rota física validada. Pilares enviados ao Arquivo.':'Os detalhes não formam uma rota contínua. Revise reflexo, acesso e vestígio.';if(ok){state.roundDone.add(state.round);r.reward.forEach(x=>{if(!state.archive.includes(x))state.archive.push(x)});renderArchive();setTimeout(()=>{if(state.round<2)state.round++;renderInvestigation()},450)}};renderArchive()}
function renderArchive(){document.getElementById('archiveCount').textContent=`${state.archive.length} evidências validadas`;document.getElementById('archiveTags').innerHTML=state.archive.map(x=>`<span class="tag">${x}</span>`).join('');document.getElementById('toHypothesis').disabled=state.roundDone.size<3}
document.getElementById('toHypothesis').onclick=()=>{buildHypothesis();goto('hypothesis')};
function options(arr){return arr.map((x,i)=>`<option value="${i?x:''}">${x}</option>`).join('')}
function buildHypothesis(){const f=document.getElementById('hypothesisForm');f.suspect.innerHTML=options(suspects);f.motive.innerHTML=options(motives);f.action.innerHTML=options(actions);document.getElementById('evidenceChoices').innerHTML=evidence.map((x,i)=>`<label class="choice"><input type="radio" name="evidence" value="${x}" ${i===0?'required':''}>${x}</label>`).join('')}
document.getElementById('hypothesisForm').onsubmit=e=>{e.preventDefault();state.hypothesis=Object.fromEntries(new FormData(e.target));buildMarket();goto('market')};
function buildMarket(){document.getElementById('credits').textContent=state.credits;document.getElementById('marketGrid').innerHTML=lots.map((l,i)=>`<article class="lot ${state.bought.has(i)?'open':''}"><span>${l.type}</span><h3>${l.name}</h3><p>${state.bought.has(i)?l.result:l.text}</p><button data-lot="${i}" ${state.bought.has(i)?'disabled':''}>${state.bought.has(i)?'ADQUIRIDO':`ABRIR · ${l.cost} CR`}</button></article>`).join('');document.querySelectorAll('[data-lot]').forEach(b=>b.onclick=()=>{const i=+b.dataset.lot,l=lots[i];if(state.credits<l.cost){document.getElementById('marketLog').textContent='Créditos insuficientes. Escolha outro lote.';return}state.credits-=l.cost;state.bought.add(i);document.getElementById('marketLog').textContent=l.result;buildMarket()});document.getElementById('leaveMarket').disabled=state.bought.size<2}
document.getElementById('leaveMarket').onclick=()=>{buildMosaic();goto('mosaic')};
function buildMosaic(){document.getElementById('oldHypothesis').textContent=`Você apontou: ${state.hypothesis.suspect}`;document.getElementById('routeGrid').innerHTML=routes.map(r=>`<article class="route-card" data-route="${r.id}"><span>ROTA DE DEDUÇÃO</span><h3>${r.id}</h3><ol>${r.items.map(x=>`<li>${x}</li>`).join('')}</ol></article>`).join('');document.querySelectorAll('.route-card').forEach(c=>c.onclick=()=>{document.querySelectorAll('.route-card').forEach(x=>x.classList.remove('selected'));c.classList.add('selected');state.route=c.dataset.route;checkMosaic()});document.getElementById('counterAxes').innerHTML=['tempo','acesso','objeto','origem','comunicação','sistema'].map(x=>`<button class="axis" data-axis="${x}">${x}</button>`).join('');document.querySelectorAll('.axis').forEach(b=>b.onclick=()=>{document.querySelectorAll('.axis').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.axis=b.dataset.axis;checkMosaic()})}
function checkMosaic(){document.getElementById('toFinal').disabled=!(state.route&&state.axis)}document.getElementById('toFinal').onclick=()=>{buildFinal();goto('final')};
function buildFinal(){document.getElementById('finalForm').innerHTML=`<label>Suspeito Principal<select name="suspect" required>${options(suspects)}</select></label><label>Motivo<select name="motive" required>${options(motives)}</select></label><label>Ação decisiva<select name="action" required>${options(actions)}</select></label><label>Prova-chave<select name="evidence" required>${options(['Selecione…',...evidence])}</select></label><label>Lacuna resolvida<select name="gap" required>${options(['Selecione…','Autorização negligente do Gerente','Horário da farmácia','Pasta azul','Rota incomum'])}</select></label><button class="primary" type="submit">Enviar dedução final</button>`}
document.getElementById('finalForm').onsubmit=e=>{e.preventDefault();state.final=Object.fromEntries(new FormData(e.target));state.reveal=0;goto('reveal');showReveal()};
const revealSteps=[
 ()=>`<div><span class="kicker">A ESPINHA · 87 SEGUNDOS</span><h2>A câmera apagou.<br>O percurso continuou.</h2><div class="timeline-visual"><i></i></div><p>O Segurança é afastado. A porta abre. O malote entra nos arquivos, recebe outra etiqueta e termina no chão.</p></div>`,
 ()=>`<div><span class="kicker">O NOME</span><h2>O Subgerente coordenou.<br><em>A Limpeza executou.</em></h2><p>17—B não era uma pane: era a diferença da auditoria convertida em instrução, acesso e tempo.</p></div>`,
 ()=>`<div><span class="kicker">ROTA ${state.route?.toUpperCase()}</span><h2>As peças não acusam sozinhas.</h2><p>${routes.find(r=>r.id===state.route)?.items.join(' → ')}. Duas rotas independentes sustentam a mesma verdade.</p></div>`,
 ()=>`<div><span class="kicker">UMA VOZ</span><h2>“Oitenta e sete segundos cabem dentro de uma obediência.”</h2><p>O Segurança reconheceu a voz antes de reconhecer o perigo. Quando voltou, a câmera já respirava de novo.</p></div>`,
 ()=>`<div><span class="kicker">CONSEQUÊNCIAS</span><h2>A manhã não termina no nome.</h2><p>O que a mesa sustentou agora decide quem é protegido, quem é queimado e quanto da porta lateral permanece aberto.</p></div>`
];
function showReveal(){document.getElementById('revealStage').innerHTML=revealSteps[state.reveal]();const b=document.getElementById('nextReveal');b.classList.remove('hidden');b.innerHTML=state.reveal===revealSteps.length-1?'Ver placar <span>→</span>':'Continuar revelação <span>→</span>'}
document.getElementById('nextReveal').onclick=()=>{state.reveal++;if(state.reveal>=revealSteps.length){calculateScore();goto('score')}else showReveal()};
function calculateScore(){const correct=state.final.suspect==='Subgerente';const q=(state.final.motive===motives[1]?5:0)+(state.final.action===actions[1]?5:0)+(state.final.gap==='Autorização negligente do Gerente'?3:0);const scores={Tempo:correct?28:0,Qualidade:correct?q:0,Cooperação:state.joined.size===state.players?26:18,'Economia e Risco':15,Performance:4};const total=Object.values(scores).reduce((a,b)=>a+b,0);document.getElementById('totalScore').textContent=total;document.getElementById('scoreTitle').textContent=correct?'Vocês encontraram o nome. Agora carregam as consequências.':'A auditoria corrigiu o nome. O dano da acusação permaneceu.';document.getElementById('scoreBars').innerHTML=Object.entries(scores).map(([k,v])=>{const max={Tempo:32,Qualidade:13,Cooperação:30,'Economia e Risco':20,Performance:5}[k];return`<div class="score-row"><span>${k}</span><div class="bar"><i style="width:${v/max*100}%"></i></div><b>${v}/${max}</b></div>`}).join('');const cards=[correct?['D01','A denúncia correta','A cadeia de prova chega íntegra à auditoria.']:['D02','O nome corrigido','A auditoria corrige a pessoa, mas registra o dano.'],state.route==='Relógio'?['D05','Rota Relógio','O recibo do Veterano vira âncora pública.']:state.route==='Acesso'?['D06','Rota Acesso','O banco revê todas as chaves de serviço.']:['D07','Código 17—B','O número vira assinatura documental.'],state.final.action===actions[1]?['D03','Autor e executor','O processo separa coordenação e execução.']:['D04','O nome que faltou','As chaves localizam o cúmplice depois.']];document.getElementById('endingCards').innerHTML=cards.map(c=>`<article class="ending-card"><b>${c[0]}</b><h3>${c[1]}</h3><p>${c[2]}</p></article>`).join('')}
function saveGame(){const data={...state,joined:[...state.joined],roundDone:[...state.roundDone],bought:[...state.bought]};localStorage.setItem('mosaico-v3-save',JSON.stringify(data))}
setInterval(()=>{const s=Math.floor((Date.now()-state.start)/1000);document.getElementById('timer').textContent=`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;saveGame()},1000);
function resumeGame(){const raw=localStorage.getItem('mosaico-v3-save');if(!raw)return;const data=JSON.parse(raw);Object.assign(state,data,{joined:new Set(data.joined||[]),roundDone:new Set(data.roundDone||[]),bought:new Set(data.bought||[])});if(state.screen==='pieces')renderPlayers();if(state.screen==='investigation')renderInvestigation();if(state.screen==='hypothesis')buildHypothesis();if(state.screen==='market')buildMarket();if(state.screen==='mosaic')buildMosaic();if(state.screen==='final')buildFinal();if(state.screen==='reveal')showReveal();if(state.screen==='score')calculateScore();goto(state.screen==='intro'?'briefing':state.screen)}
const resume=document.getElementById('resumeBtn');if(localStorage.getItem('mosaico-v3-save'))resume.classList.remove('hidden');resume.onclick=resumeGame;
document.getElementById('resetBtn').onclick=()=>{localStorage.removeItem('mosaico-v3-save');location.reload()};document.getElementById('playAgain').onclick=()=>{localStorage.removeItem('mosaico-v3-save');location.reload()};
function openReviewScreen(name){state.players=6;state.hypothesis={suspect:'Estagiária',motive:'Erro humano',action:'Trocar a pasta azul',evidence:evidence[5]};state.route='Acesso';state.axis='acesso';state.final={suspect:'Subgerente',motive:motives[1],action:actions[1],evidence:evidence[4],gap:'Autorização negligente do Gerente'};if(name==='briefing'){goto(name);return}if(name==='pieces')renderPlayers();if(name==='investigation')renderInvestigation();if(name==='hypothesis')buildHypothesis();if(name==='market')buildMarket();if(name==='mosaic')buildMosaic();if(name==='final')buildFinal();if(name==='reveal'){state.reveal=2;showReveal()}if(name==='score')calculateScore();goto(name)}
const reviewScreen=new URLSearchParams(location.search).get('review');if(reviewScreen)setTimeout(()=>openReviewScreen(reviewScreen),80);
