/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EscuroRouteImport } from './routes/escuro'
import { Route as NoiteRouteImport } from './routes/noite'
import { Route as PlayRouteImport } from './routes/play'
import { Route as NoiteIndexRouteImport } from './routes/noite.index'
import { Route as NoiteSlugRouteImport } from './routes/noite.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EscuroRoute = EscuroRouteImport.update({
  id: '/escuro',
  path: '/escuro',
  getParentRoute: () => rootRouteImport,
} as any)
const NoiteRoute = NoiteRouteImport.update({
  id: '/noite',
  path: '/noite',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRoute = PlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => rootRouteImport,
} as any)
const NoiteIndexRoute = NoiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NoiteRoute,
} as any)
const NoiteSlugRoute = NoiteSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NoiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/escuro': typeof EscuroRoute
  '/noite': typeof NoiteRouteWithChildren
  '/play': typeof PlayRoute
  '/noite/$slug': typeof NoiteSlugRoute
  '/noite/': typeof NoiteIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/escuro': typeof EscuroRoute
  '/play': typeof PlayRoute
  '/noite/$slug': typeof NoiteSlugRoute
  '/noite': typeof NoiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/escuro': typeof EscuroRoute
  '/noite': typeof NoiteRouteWithChildren
  '/play': typeof PlayRoute
  '/noite/$slug': typeof NoiteSlugRoute
  '/noite/': typeof NoiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/escuro' | '/noite' | '/play' | '/noite/$slug' | '/noite/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/escuro' | '/play' | '/noite/$slug' | '/noite'
  id:
    | '__root__'
    | '/'
    | '/escuro'
    | '/noite'
    | '/play'
    | '/noite/$slug'
    | '/noite/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EscuroRoute: typeof EscuroRoute
  NoiteRoute: typeof NoiteRouteWithChildren
  PlayRoute: typeof PlayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escuro': {
      id: '/escuro'
      path: '/escuro'
      fullPath: '/escuro'
      preLoaderRoute: typeof EscuroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noite': {
      id: '/noite'
      path: '/noite'
      fullPath: '/noite'
      preLoaderRoute: typeof NoiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play': {
      id: '/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof PlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noite/': {
      id: '/noite/'
      path: '/'
      fullPath: '/noite/'
      preLoaderRoute: typeof NoiteIndexRouteImport
      parentRoute: typeof NoiteRoute
    }
    '/noite/$slug': {
      id: '/noite/$slug'
      path: '/$slug'
      fullPath: '/noite/$slug'
      preLoaderRoute: typeof NoiteSlugRouteImport
      parentRoute: typeof NoiteRoute
    }
  }
}

interface NoiteRouteChildren {
  NoiteSlugRoute: typeof NoiteSlugRoute
  NoiteIndexRoute: typeof NoiteIndexRoute
}

const NoiteRouteChildren: NoiteRouteChildren = {
  NoiteSlugRoute: NoiteSlugRoute,
  NoiteIndexRoute: NoiteIndexRoute,
}

const NoiteRouteWithChildren = NoiteRoute._addFileChildren(NoiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EscuroRoute: EscuroRoute,
  NoiteRoute: NoiteRouteWithChildren,
  PlayRoute: PlayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
