'use strict';
const ORDEM=['sete','cinco','apagao','nome','corpo','perceber'];
const CHAVE_ROT='mosaico_casa_ultima_partida_solo';
const EVID={
 f1:{title:'As sete xícaras',icon:'☕',fact:'Sete xícaras limpas estavam secando na pia. Seis pessoas beberam chá naquela noite.',relation:'xícaras + poeira + despensa',inference:'rotina de habitação'},
 f2:{title:'A ausência de poeira',icon:'✦',fact:'Cozinha e corredor têm menos poeira que os demais cômodos após cinco meses de casa fechada.',relation:'xícaras + poeira + despensa',inference:'rotina de habitação'},
 f3:{title:'A despensa',icon:'▤',fact:'As latas seguem um padrão de organização compatível com uso continuado.',relation:'xícaras + poeira + despensa',inference:'rotina de habitação'},
 f4:{title:'O quarto degrau',icon:'⌁',fact:'O quarto degrau range sob carga; foi ouvido quando ninguém dos seis estava na escada.',relation:'degrau + colher + cadeira',inference:'massa e temperatura'},
 f5:{title:'A colher',icon:'⌇',fact:'Uma colher surgiu no piso do corredor após o apagão; não estava ali às 21h19.',relation:'degrau + colher + cadeira',inference:'objeto deslocado'},
 f6:{title:'A respiração',icon:'≈',fact:'A Jornalista ouviu respiração muito próxima durante o escuro, em ponto sem outro integrante do grupo.',relation:'respiração + sombra + posições',inference:'ponto ocupado'},
 f7:{title:'A sombra',icon:'◐',fact:'O Policial percebeu um vulto cruzando o corredor, compatível com um corpo entre ele e a janela.',relation:'respiração + sombra + posições',inference:'ponto ocupado'},
 f8:{title:'O nome',icon:'✉',fact:'Às 21h31 a secretária eletrônica reiniciou e reproduziu um nome que não pertence a nenhum dos seis.',relation:'nome + contrato',inference:'identidade da sétima pessoa'},
 f9:{title:'O contrato',icon:'§',fact:'O espólio registra pagamento de uma acompanhante por catorze meses, encerrado há cinco meses.',relation:'nome + contrato',inference:'identidade e período'},
 f10:{title:'As pegadas',icon:'⋰',fact:'No jardim interno há pegadas que entram e não saem, com numeração diferente da de todos os presentes.',relation:'pegadas + porta do jardim',inference:'localização'},
 f11:{title:'A porta do jardim',icon:'▯',fact:'A porta do antigo quarto de serviço está sem tranca e com dobradiça lubrificada recentemente.',relation:'pegadas + porta do jardim',inference:'quarto de serviço'},
 f12:{title:'A cadeira morna',icon:'♨',fact:'Às 21h35 uma cadeira do corredor estava acima da temperatura ambiente.',relation:'degrau + colher + cadeira',inference:'calor corporal'},
 f13:{title:'O consumo',icon:'◒',fact:'O hidrômetro mostra consumo diário durante os cinco meses em que a casa esteve considerada vazia.',relation:'consumo + visitas',inference:'ocupação contínua'},
 f14:{title:'O boiler',icon:'♨',fact:'Há acionamentos do boiler em dias diferentes das visitas semanais do Morador.',relation:'consumo + visitas',inference:'ocupação contínua'},
 f15:{title:'Queda em rede',icon:'⚡',fact:'A concessionária confirma interrupção às 21h29 em três casas da encosta e retorno às 21h31.',relation:'apagão + rede + disjuntor',inference:'apagão externo'},
 f16:{title:'O disjuntor',icon:'⏻',fact:'A chave geral permaneceu ligada e não apresenta sinal de acionamento manual.',relation:'apagão + rede + disjuntor',inference:'apagão não provocado'},
 f17:{title:'Caixa de passagem',icon:'▣',fact:'A caixa enterrada no jardim foi encontrada submersa, com oxidação recente.',relation:'apagão + rede + disjuntor',inference:'causa da queda'},
 f19:{title:'O higrômetro',icon:'⌁',fact:'Picos de umidade coincidem com os estalos regulares do sótão.',relation:'umidade + estalos',inference:'fenômeno estrutural'},
 f20:{title:'O cofre',icon:'□',fact:'O cofre estava apenas encostado; o envelope do inventário permanecia íntegro e nada foi subtraído.',relation:'cofre + envelope',inference:'não houve furto'}
};
const SETS={sete:['f1','f2','f4','f6','f7','f10','f9','f11'],cinco:['f1','f2','f3','f13','f14','f9'],apagao:['f4','f5','f6','f7','f15','f16','f17'],nome:['f8','f9','f13','f11'],corpo:['f19','f15','f4','f6','f7','f12','f20'],perceber:['f2','f13','f14','f9','f11','f1']};
const state={phase:'home',caso:null,key:null,i:0,order:[0,1,2,3],pick:null,seen:[],facts:{},answers:{},scoreFacts:0};
const app=document.getElementById('app');
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function shuffle(a){a=a.slice();for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function valida(k){return !!(state.caso&&state.caso.partidas&&state.caso.partidas[k]&&SETS[k]);}
function proxima(){let u='';try{u=localStorage.getItem(CHAVE_ROT)||''}catch(e){}let i=ORDEM.indexOf(u);for(let n=1;n<=ORDEM.length;n++){let k=ORDEM[(i+n+ORDEM.length)%ORDEM.length];if(valida(k))return k}return state.caso.perguntaPadrao||'sete';}
function marcarUsada(){try{localStorage.setItem(CHAVE_ROT,state.key)}catch(e){}}
function header(){return '<div class="shell"><div class="top"><div class="brand">MOSAICO · MODO SOLO</div><div class="badge">A Casa da Costa · 1867</div></div>';}
async function load(){try{const r=await fetch('../v1/casos/casa-da-costa.json?v=20260830-auto');if(!r.ok)throw Error();state.caso=await r.json();state.key=proxima();}catch(e){app.innerHTML=header()+'<div class="hero"><span class="k">Falha de carregamento</span><h2>O caso não pôde ser aberto.</h2><p class="muted">Recarregue a página quando a conexão estiver disponível.</p></div></div>';return;}render();}
function render(){if(!state.caso)return;let h=header();if(state.phase==='home')h+=home();if(state.phase==='puzzle')h+=puzzle();if(state.phase==='fact')h+=fact();if(state.phase==='relations')h+=relations();if(state.phase==='map')h+=map();if(state.phase==='decision')h+=decision();if(state.phase==='result')h+=result();app.innerHTML=h+'</div>';}
function home(){let p=state.caso.partidas[state.key];return '<section class="hero"><span class="k">Uma verdade · uma nova pergunta</span><h1>A verdade é um fragmento.</h1><p class="lead">Reconstrua sozinho as evidências da Casa da Costa. O MOSAICO escolheu automaticamente o problema desta execução.</p><div class="question"><b>'+esc(p.natureza)+' · pergunta-mãe</b><p>'+esc(p.pergunta)+'</p></div><button class="btn" onclick="start()">Começar reconstrução</button><p class="muted small" style="margin-top:16px">Ao concluir, a próxima execução avançará automaticamente para outra pergunta da mesma realidade.</p></section>';}
function start(){marcarUsada();state.i=0;state.seen=[];state.facts={};state.answers={};state.scoreFacts=0;state.phase='puzzle';newPuzzle();render();}
function currentId(){return SETS[state.key][state.i];}
function newPuzzle(){state.order=shuffle([0,1,2,3]);if(state.order.every((v,i)=>v===i))[state.order[0],state.order[1]]=[state.order[1],state.order[0]];state.pick=null;}
function puzzle(){let id=currentId(),e=EVID[id],p=state.caso.partidas[state.key],pct=Math.round(state.i/SETS[state.key].length*100);let pieces=state.order.map((n,i)=>'<button class="piece '+(state.pick===i?'sel ':'')+(n===i?'ok':'')+'" data-mark="'+esc(e.icon)+'" onclick="tap('+i+')"><span style="position:absolute;left:7px;top:5px;font-size:10px;opacity:.6">'+(n+1)+'</span></button>').join('');return '<div class="stage"><div><span class="k">'+esc(p.titulo)+'</span><h2>Evidência '+(state.i+1)+' de '+SETS[state.key].length+'</h2></div><div class="badge">'+pct+'%</div></div><div class="progress"><i style="width:'+pct+'%"></i></div><div class="evidence"><div class="meta"><span>Arquivo fragmentado</span><span>'+esc(id.toUpperCase())+'</span></div><h3>'+esc(e.title)+'</h3><div class="puzzle">'+pieces+'</div><p class="muted" style="color:#59452e">Toque em duas peças para trocar suas posições.</p></div>';}
function tap(i){if(state.pick===null){state.pick=i;render();return;}if(state.pick===i){state.pick=null;render();return;}let a=state.pick;[state.order[a],state.order[i]]=[state.order[i],state.order[a]];state.pick=null;if(state.order.every((v,n)=>v===n))state.phase='fact';render();}
function factOptions(e){return shuffle([e.fact,'Esse fato sozinho identifica quem estava na casa.','Esse fato prova que houve crime.','Esse fato já explica toda a noite.']);}
function fact(){let id=currentId(),e=EVID[id];if(!state.facts[id])state.facts[id]={opts:factOptions(e),chosen:null};let f=state.facts[id];let opts=f.opts.map((o,i)=>'<button class="opt '+(f.chosen===i?(o===e.fact?'good':'bad'):'')+'" onclick="chooseFact('+i+')">'+esc(o)+'</button>').join('');return '<span class="k">FATO</span><h2>O que esta evidência permite afirmar diretamente?</h2><div class="factbox"><b>'+esc(e.title)+'</b><span>Evite transformar pista em conclusão.</span></div><div class="opts">'+opts+'</div>'+(f.chosen!==null?'<button class="btn" onclick="nextEvidence()">'+(state.i<SETS[state.key].length-1?'Próxima evidência':'Relacionar fatos')+'</button>':'');}
function chooseFact(i){let id=currentId(),e=EVID[id],f=state.facts[id];if(f.chosen!==null)return;f.chosen=i;if(f.opts[i]===e.fact)state.scoreFacts++;render();}
function nextEvidence(){let id=currentId();if(!state.seen.includes(id))state.seen.push(id);if(state.i<SETS[state.key].length-1){state.i++;newPuzzle();state.phase='puzzle';}else state.phase='relations';render();}
function relationGroups(){let g={};SETS[state.key].forEach(id=>{let e=EVID[id];(g[e.relation]||(g[e.relation]=[])).push(id)});return Object.entries(g).filter(x=>x[1].length>1);}
function relations(){let groups=relationGroups();let html=groups.map(([r,ids],idx)=>'<div class="relation"><span class="k">RELAÇÃO '+(idx+1)+'</span><h3>'+ids.map(id=>esc(EVID[id].title)).join(' + ')+'</h3><div class="tags">'+ids.map(id=>'<span class="tag">'+esc(EVID[id].fact.split('.')[0])+'</span>').join('')+'</div><p class="muted">Juntos, esses fatos sustentam: <b style="color:var(--gold2)">'+esc(EVID[ids[0]].inference)+'</b>.</p></div>').join('');return '<span class="k">FATO → RELAÇÃO → INFERÊNCIA</span><h2>Agora os fragmentos começam a conversar.</h2><p class="lead">Uma pista isolada é fraca. A relação entre fatos é o que torna a inferência auditável.</p>'+html+'<button class="btn" onclick="state.phase=\'map\';render()">Abrir a planta de 1867</button>';}
function map(){let p=state.caso.partidas[state.key];return '<span class="k">MAPA DA CASA</span><h2>Onde os fatos se encontram?</h2><p class="lead">Use a planta como síntese espacial. Não procure um culpado: procure onde a pergunta começa a fechar.</p><div class="map"><img src="../v1/img/casa-da-costa-planta-1867.svg" alt="Planta esquemática da Casa da Costa, construção de 1867"><div class="mapnote"><b>'+esc(p.titulo)+'</b><br>'+esc(p.pergunta)+'</div></div><button class="btn" onclick="state.phase=\'decision\';render()">Responder à pergunta</button>';}
function decision(){let p=state.caso.partidas[state.key];let fields=p.campos.map(f=>'<div class="field"><label>'+esc(f.rotulo)+'</label><select id="f-'+esc(f.id)+'"><option value="">Escolha…</option>'+f.opcoes.map(o=>'<option>'+esc(o)+'</option>').join('')+'</select></div>').join('');return '<span class="k">INFERÊNCIA → DECISÃO</span><h2>'+esc(p.pergunta)+'</h2><p class="lead">Preencha os campos derivados desta pergunta. Depois do envio, a resposta será comparada à realidade canônica.</p><div class="fields">'+fields+'</div><button class="btn red" onclick="finish()">Fechar minha conclusão</button><button class="btn ghost" onclick="state.phase=\'relations\';render()">Rever relações</button>';}
function finish(){let p=state.caso.partidas[state.key],all=true,correct=0;state.answers={};p.campos.forEach(f=>{let el=document.getElementById('f-'+f.id),v=el?el.value:'';if(!v)all=false;state.answers[f.id]=v;if(v===f.resposta)correct++});if(!all){alert('Preencha todos os campos antes de fechar a conclusão.');return;}state.correct=correct;state.phase='result';render();}
function result(){let p=state.caso.partidas[state.key],total=p.campos.length,fieldPct=Math.round(100*state.correct/total),factPct=Math.round(100*state.scoreFacts/SETS[state.key].length),score=Math.round(fieldPct*.7+factPct*.3);let rows=p.campos.map(f=>'<div class="relation"><span class="k">'+esc(f.rotulo)+'</span><p style="margin:.35rem 0"><b>Sua resposta:</b> '+esc(state.answers[f.id])+'</p><p class="muted" style="margin:0"><b>Canônica:</b> '+esc(f.resposta)+'</p></div>').join('');return '<span class="k">REVELAÇÃO</span><h2>'+esc(p.titulo)+'</h2><div class="result"><div class="score">'+score+'</div><p class="muted">Índice desta execução · 30% leitura factual + 70% decisão</p><p class="lead">'+esc(p.revelacao)+'</p></div>'+rows+'<div class="factbox"><b>Realidade canônica</b><span>'+esc(state.caso.realidadeCanonica.sintese)+'</span></div><button class="btn" onclick="nextRun()">Nova partida</button>';}
function nextRun(){state.key=proxima();state.phase='home';state.i=0;state.seen=[];state.facts={};state.answers={};state.scoreFacts=0;render();}
load();