const QUESTIONS={peso:{nature:'QUANTO + QUANDO',title:'O Peso do Malote 41',question:'O banco anuncia que faltam quatrocentos e oitenta mil reais. Quanto realmente desapareceu?',hook:'Um número parece óbvio. A direção do dinheiro não.',fields:['Valor declarado','Valor físico real','Movimentação da manhã','Diferença real','Data de origem'],answers:['R$ 480.000','R$ 384.000','+ R$ 96.000','R$ 0','Onze dias antes']},janela:{nature:'O QUÊ + COMO',title:'Os 87 Segundos',question:'O que realmente aconteceu enquanto a câmera 3 ficou cega?',hook:'Reconstrua a janela sem pressupor retirada.',fields:['Primeiro evento','Intervenção no malote','Lacre','Direção do fluxo','Fim da janela'],answers:['Rádio afasta Vigilância','R$ 96.000 entram','ML-8847 substitui ML-8842','Fora → dentro do malote','7h59min39s']},roubo:{nature:'QUAL / QUE TIPO',title:'Foi um roubo?',question:'Todo mundo viu os sinais de um assalto. Mas houve realmente um roubo?',hook:'Irregularidade não é sinônimo de subtração.',fields:['Natureza da manhã','Houve subtração?','Falha da câmera','Natureza da diferença','Leitura “só bagunça”'],answers:['Encenação operacional','Não','Deliberadamente preparada','Escritural','Parcialmente correta']},antes:{nature:'QUANDO',title:'Antes das 8h02',question:'Quando nasceu a diferença que todos procuram?',hook:'A mesa olha para minutos. A resposta está onze dias atrás.',fields:['Âncora da manhã','Janela crítica','Origem da duplicidade','Evento de urgência','Diferença física'],answers:['7h47','87 segundos','Onze dias antes','Auditoria na véspera','Nunca nasce']},quem:{nature:'QUEM COMPOSTO',title:'Quem construiu a janela?',question:'Quem colocou cada peça daqueles 87 segundos em movimento?',hook:'Decisão, preparação, execução e negligência não são a mesma coisa.',fields:['Quem decide','Quem prepara','Quem abre sem conhecer a finalidade','Quem executa o reset','Quem autoriza sem contingência'],answers:['Subgerente','Subgerente','Limpeza','Manutenção','Gerência']},proteger:{nature:'POR QUÊ',title:'O que estava sendo protegido?',question:'Se não era o dinheiro, o que alguém estava tentando salvar?',hook:'A ação material contradiz o motivo aparente.',fields:['Objeto protegido','Função dos R$ 96.000','Gatilho de urgência','Ato original ocultado','Objetivo final'],answers:['Assinatura e carreira','Completar o saldo físico','Auditoria integral','Assinatura sem conferência','Fazer registro e físico coincidirem']}};
const FRAGMENTS=[{id:'F2',title:'Âncora 7h47',text:'Recibo, cafeteira e chegada do veículo fixam 7h47.'},{id:'F5',title:'Zona cega',text:'A câmera 3 fica fora entre 7h58min12s e 7h59min39s.'},{id:'F7',title:'Duas etiquetas',text:'ML-8842 aparece rompido; ML-8847 foi impresso às 7h53.'},{id:'F8',title:'O saco vazio',text:'O saco encontrado às 8h02 pesa 0,4 kg.'},{id:'F9',title:'O peso',text:'O malote entregue à custódia pesa 5,1 kg.'},{id:'F10',title:'Conferência',text:'Às 8h40 a tesouraria confirma R$ 480.000 íntegros.'},{id:'F11',title:'Saque pessoal',text:'Às 6h20, R$ 96.000 saem de recursos pessoais da subgerência.'},{id:'F13',title:'Duplicidade',text:'Um único depósito de R$ 96.000 aparece duas vezes na consolidação D-11.'},{id:'F14',title:'Assinatura',text:'A consolidação foi assinada sem abertura física do cofre.'},{id:'F15',title:'Auditoria',text:'Às 21h47 da véspera chega convocação para contagem integral.'},{id:'F16',title:'Trajeto',text:'Marcas de água e sensor ligam mesa, arquivos e retorno à custódia.'}];
const LAB=new URLSearchParams(location.search).get('soloLab')==='1';
const BOT_NAMES=['Helena','Augusto','Lia','Rafael','Beatriz','Caio','Nina'];
const BOT_PROFILES=['analítico','cauteloso','intuitivo','impulsivo','documental','explorador','revisionista'];
const state={screen:'intro',players:LAB?8:6,question:null,pace:30,turn:0,coins:12,hand:[],opponents:[],locked:new Set(),burned:new Set(),timer:null,left:30,bots:[]};
const screens=[...document.querySelectorAll('.screen')];
function go(name){screens.forEach(s=>s.classList.toggle('active',s.dataset.screen===name));state.screen=name;scrollTo(0,0)}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function toast(msg){const old=document.querySelector('.toast');old?.remove();const t=document.createElement('div');t.className='toast depth-card';t.textContent=msg;Object.assign(t.style,{position:'fixed',left:'50%',bottom:'96px',transform:'translateX(-50%)',zIndex:80,padding:'11px 15px',maxWidth:'90vw',fontSize:'12px',color:'#f3f6f4'});document.body.appendChild(t);setTimeout(()=>t.remove(),1800)}
function initBots(){if(!LAB)return;state.players=8;state.bots=BOT_NAMES.map((name,i)=>({name,profile:BOT_PROFILES[i],coins:12,hand:shuffle([...FRAGMENTS]).slice(0,3),locked:new Set(),burned:new Set(),hypothesis:'em aberto',changes:0,actions:0}));window.MosaicoSoloLab={active:true,bots:state.bots,started:Date.now(),events:[],log(type,data){this.events.push({ms:Date.now()-this.started,type,...data})}};const sel=document.getElementById('playerCount');if(sel){sel.value='8';sel.disabled=true}}
function resetTimer(){clearInterval(state.timer);state.left=state.pace;paintTimer();if(LAB&&state.turn>0){scheduleBotTurn();return}state.timer=setInterval(()=>{state.left--;paintTimer();if(state.left<=0){clearInterval(state.timer);nextTurn('Tempo encerrado. A mão foi perdida.')}},1000)}
function paintTimer(){const el=document.getElementById('turnTimer');if(el)el.textContent=`00:${String(Math.max(0,state.left)).padStart(2,'0')}`}
function nextTurn(message='Ação concluída.'){state.turn=(state.turn+1)%state.players;document.getElementById('turnPlayer').textContent=state.turn===0?'Você':LAB?state.bots[state.turn-1].name:`Arquivo ${String(state.turn+1).padStart(2,'0')}`;toast(message);resetTimer()}
function scheduleBotTurn(){clearInterval(state.timer);const b=state.bots[state.turn-1];if(!b)return nextTurn();const think=650+Math.floor(Math.random()*1200);state.left=Math.max(1,Math.ceil(think/1000));paintTimer();setTimeout(()=>{if(state.screen!=='table'||state.turn===0)return;botAct(b)},think)}
function botAct(b){const q=QUESTIONS[state.question],available=FRAGMENTS.filter(f=>!b.hand.some(h=>h.id===f.id));let action='observar';if(b.coins>=4&&available.length&&Math.random()<.46){b.coins-=4;b.hand.push(available[Math.floor(Math.random()*available.length)]);action='comprou fragmento'}else{const open=q.fields.map((_,i)=>i).filter(i=>!b.locked.has(i)&&!b.burned.has(i));if(b.coins>=3&&open.length){const i=open[Math.floor(Math.random()*open.length)];const bonus=(b.profile==='analítico'||b.profile==='documental')?.12:0;const knowledge=Math.min(.86,.28+b.hand.length*.075+bonus);b.coins-=3;if(Math.random()<knowledge){b.locked.add(i);b.coins+=3;action='travou '+q.fields[i]}else{b.burned.add(i);action='errou '+q.fields[i]}}}const old=b.hypothesis;if(b.locked.size>=2)b.hypothesis=`${b.locked.size} campos sustentados`;if(old!=='em aberto'&&old!==b.hypothesis)b.changes++;b.actions++;window.MosaicoSoloLab?.log('bot-turn',{bot:b.name,action,hypothesis:b.hypothesis});syncBotOpponents();nextTurn(`${b.name} · ${action}.`)}
function renderQuestions(){const host=document.getElementById('questionGrid');host.innerHTML=Object.entries(QUESTIONS).map(([id,q])=>`<button class="question-card depth" data-q="${id}" type="button"><small>${q.nature}</small><h3>${q.title}</h3><p>${q.question}</p><b>${q.hook}</b></button>`).join('');host.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>{state.question=b.dataset.q;const q=QUESTIONS[state.question];document.getElementById('paceTitle').textContent=q.title;document.getElementById('paceQuestion').textContent=q.question;go('pace')})}
function setupTable(){const q=QUESTIONS[state.question];state.coins=12;state.turn=0;state.locked.clear();state.burned.clear();state.hand=shuffle([...FRAGMENTS]).slice(0,3);if(LAB){initBots();syncBotOpponents()}else state.opponents=Array.from({length:state.players-1},(_,i)=>({name:`Arquivo ${String(i+2).padStart(2,'0')}`,count:2+(i%3)}));document.getElementById('gameNature').textContent=q.nature;document.getElementById('gameTitle').textContent=q.title;document.getElementById('questionBanner').textContent=q.question;document.getElementById('turnPlayer').textContent=LAB?'Você':'Arquivo 01';renderAll();go('table');resetTimer()}
function syncBotOpponents(){if(!LAB)return;state.opponents=state.bots.map(b=>({name:`${b.name} · ${b.profile}`,count:b.hand.length,status:b.hypothesis}))}
function renderAll(){renderHand();renderFields();renderOpponents();document.getElementById('coins').textContent=state.coins}
function renderHand(){const host=document.getElementById('hand');host.innerHTML=state.hand.map(f=>`<article class="fragment depth" data-f="${f.id}"><small>${f.id}</small><strong>${f.title}</strong><p>${f.text}</p></article>`).join('');document.getElementById('handCount').textContent=state.hand.length;host.querySelectorAll('[data-f]').forEach(c=>c.onclick=()=>openFragment(c.dataset.f))}
function renderFields(){const q=QUESTIONS[state.question],host=document.getElementById('fields');host.innerHTML=q.fields.map((f,i)=>`<div class="field-row ${state.locked.has(i)?'locked':''} ${state.burned.has(i)?'burned':''}"><div><b>${f}</b><span>${state.locked.has(i)?'TRAVADO PARA A MESA':state.burned.has(i)?'QUEIMADO PARA VOCÊ':'ABERTO'}</span></div><span>${state.locked.has(i)?'✓':state.burned.has(i)?'×':'○'}</span></div>`).join('')}
function renderOpponents(){document.getElementById('opponents').innerHTML=state.opponents.map(o=>`<div class="opponent"><b>${o.name}</b><span>${o.count} fragmentos · ${o.status||'observando'}</span></div>`).join('')}
function openFragment(id){const f=FRAGMENTS.find(x=>x.id===id);openModal('FRAGMENTO',f.title,`<p>${f.text}</p><p><span class="tag">Fato verdadeiro</span></p>`)}
function openModal(kicker,title,body){document.getElementById('modalKicker').textContent=kicker;document.getElementById('modalTitle').textContent=title;document.getElementById('modalBody').innerHTML=body;document.getElementById('modal').showModal()}
function closeModal(){document.getElementById('modal').close()}
function actionBuy(){if(LAB&&state.turn!==0)return toast('Aguarde a vez do bot.');const cost=4;if(state.coins<cost)return toast('Moedas insuficientes.');const available=FRAGMENTS.filter(f=>!state.hand.some(h=>h.id===f.id));const choices=shuffle(available).slice(0,3);openModal('COMPRAR · 4 MOEDAS','A sorte está atrás.',`<div class="choice-list">${choices.map((f,i)=>`<button class="choice-item depth" data-buy="${f.id}" type="button"><b>Selo ${String.fromCharCode(65+i)}</b><span>Fragmento lacrado · custo 4</span></button>`).join('')}</div>`);document.querySelectorAll('[data-buy]').forEach(x=>x.onclick=()=>{const f=FRAGMENTS.find(y=>y.id===x.dataset.buy);state.coins-=cost;state.hand.push(f);renderAll();closeModal();nextTurn(`Fragmento ${f.id} incorporado.`)})}
function actionCapture(){if(LAB&&state.turn!==0)return toast('Aguarde a vez do bot.');const cost=2;if(state.coins<cost)return toast('Moedas insuficientes.');openModal('CAPTURAR · 2 MOEDAS','Escolha outro dossiê',`<div class="choice-list">${state.opponents.map((o,i)=>`<button class="choice-item depth" data-op="${i}" type="button"><b>${o.name}</b><span>${o.count} fragmentos</span></button>`).join('')}</div>`);document.querySelectorAll('[data-op]').forEach(x=>x.onclick=()=>{const op=state.opponents[+x.dataset.op],available=FRAGMENTS.filter(f=>!state.hand.some(h=>h.id===f.id));if(!available.length)return;const f=available[Math.floor(Math.random()*available.length)];state.coins-=cost;if(LAB){const bot=state.bots[+x.dataset.op];if(bot&&bot.hand.length)bot.hand.pop();syncBotOpponents()}else op.count--;state.hand.push(f);renderAll();closeModal();nextTurn(`${f.id} mudou de custódia.`)})}
function actionRisk(){if(LAB&&state.turn!==0)return toast('Aguarde a vez do bot.');const q=QUESTIONS[state.question],cost=3;if(state.coins<cost)return toast('Moedas insuficientes.');const open=q.fields.map((f,i)=>({f,i})).filter(x=>!state.locked.has(x.i)&&!state.burned.has(x.i));if(!open.length)return toast('Nenhum campo disponível para arriscar.');openModal('ARRISCAR · 3 MOEDAS','Sustente uma conclusão',`<div class="choice-list">${open.map(x=>`<button class="choice-item depth" data-field="${x.i}" type="button"><b>${x.f}</b></button>`).join('')}</div>`);document.querySelectorAll('[data-field]').forEach(b=>b.onclick=()=>riskField(+b.dataset.field))}
function riskField(i){const q=QUESTIONS[state.question],wrong=decoysFor(q.answers[i]);document.getElementById('modalTitle').textContent=q.fields[i];document.getElementById('modalBody').innerHTML=`<div class="choice-list">${shuffle([q.answers[i],...wrong]).map(v=>`<button class="choice-item depth" data-answer="${encodeURIComponent(v)}" type="button"><b>${v}</b></button>`).join('')}</div>`;document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const val=decodeURIComponent(b.dataset.answer);state.coins-=3;if(val===q.answers[i]){state.locked.add(i);state.coins+=3}else state.burned.add(i);renderAll();closeModal();nextTurn()})}
function decoysFor(answer){const pools=['R$ 480.000','R$ 384.000','R$ 96.000','R$ 0','Na manhã','Na véspera','Onze dias antes','Roubo consumado','Erro administrativo','Subgerente','Limpeza','Manutenção','Gerência','Dentro → fora','Fora → dentro'];return shuffle