/* MOSAICO · abertura audiovisual · fluxo celular estabilizado */
(function(){
const IMG='AberturaCelular.jpg',AUDIO='Amanha-do-carroforte.mp3';let armed=false,shown=false,started=false,finished=false;
const css=document.createElement('style');css.textContent=`#mosaicoPrep,#mosaicoOpening{position:fixed;inset:0;z-index:100020;background:#02070bf2;color:#eef5f2;font-family:Inter,system-ui,sans-serif;display:none;overflow:auto}#mosaicoPrep.on,#mosaicoOpening.on{display:flex}.mp-card{width:min(560px,calc(100% - 28px));margin:auto;padding:18px;border:1px solid #3d5360;border-radius:14px;background:linear-gradient(160deg,#13212b,#071016);box-shadow:0 8px 0 #020507,0 28px 70px #000b}.mp-card h2{font:600 30px Georgia,serif;margin:0 0 8px;color:#efc878}.mp-card p{color:#aab9c1;line-height:1.45}.mp-check{width:100%;min-height:54px;margin-top:10px;padding:12px 14px;border:1px solid #405866;border-radius:10px;background:#101d25;color:#eaf2f5;display:flex;align-items:center;gap:12px;font-weight:800;cursor:pointer}.mp-check input{width:22px;height:22px;accent-color:#d6aa58;flex:0 0 auto}.mp-check span{display:block;text-align:left}.mp-check small{display:block;color:#9fb0b8;font-size:12px;margin-top:3px}.mp-phone{width:100%;min-height:54px;margin-top:10px;padding:12px 14px;border:1px solid #e8a94a;border-radius:10px;background:#2a2012;color:#eaf2f5;text-align:left;font-weight:800}.mp-phone span{display:block;font-size:12px;color:#c9b995;margin-top:4px}.mp-start{width:100%;min-height:54px;margin-top:10px;padding:12px 14px;border-radius:10px;border:0;background:linear-gradient(#ffc266,#dd8b2e);color:#1b1005;text-align:center;font-weight:800}.mp-start:disabled{opacity:.38}.mp-note{margin-top:12px;padding:10px;border-left:3px solid #70d6a0;background:#0b1c16;color:#b8d7c7}.opening-stage{position:relative;width:100%;height:100%;overflow:hidden;background:#020609;display:grid;place-items:center}.opening-stage img{width:100%;height:100%;object-fit:contain}.opening-controls{position:absolute;left:50%;bottom:max(18px,env(safe-area-inset-bottom));transform:translateX(-50%);display:flex;align-items:center;justify-content:center;gap:9px;padding:9px 11px;border:1px solid #38566b;border-radius:20px;background:linear-gradient(180deg,#10212ceF,#07131beF);box-shadow:0 14px 30px #0009,inset 0 1px 0 #ffffff18;backdrop-filter:blur(10px)}.opening-controls button{width:50px;height:50px;padding:0;border:1px solid #54758a;border-radius:15px;background:linear-gradient(145deg,#17364a,#0c2230);color:#efc878;font-size:23px;font-weight:900;display:grid;place-items:center;box-shadow:0 5px 12px #0006,inset 0 1px 0 #ffffff18}.opening-controls button:active{transform:translateY(1px)}.opening-controls button[title="Pular abertura"]{color:#8ce4b0}`;document.head.appendChild(css);
const prep=document.createElement('div');prep.id='mosaicoPrep';prep.innerHTML='<div class="mp-card"><h2>📓 PREPARAR A REUNIÃO</h2><div id="mpState"></div></div>';document.body.appendChild(prep);const box=prep.querySelector('#mpState');
const opening=document.createElement('div');opening.id='mosaicoOpening';opening.innerHTML=`<div class="opening-stage"><img src="${IMG}" alt="Abertura de A Manhã do Carro-Forte"><audio id="mpAudio" preload="auto" src="${AUDIO}"></audio><div class="opening-controls"><button id="mpPlay" title="Pausar" aria-label="Pausar">Ⅱ</button><button id="mpRestart" title="Reiniciar" aria-label="Reiniciar">↻</button><button id="mpSkip" title="Pular abertura" aria-label="Pular abertura">»</button></div></div>`;document.body.appendChild(opening);const audio=opening.querySelector('#mpAudio');
function renderPrep(){box.innerHTML=`<p>A reunião está pronta. Prepare o áudio antes de iniciar a abertura neste aparelho.</p><label class="mp-check"><input type="checkbox" id="mpSound" ${armed?'checked':''}><span>🔊 Entendi · ativar som<small>${armed?'Som ativado ✓':'Marque para liberar a narração neste aparelho.'}</small></span></label><div class="mp-phone"><b>📱 Neste aparelho</b><span>Imagem e áudio no aparelho do Mestre.</span></div><div class="mp-note">A pergunta da noite só será liberada quando a abertura terminar ou quando você pular a abertura.</div><button class="mp-start" id="mpStart" ${armed?'':'disabled'}>▶ INICIAR ABERTURA</button>`;document.getElementById('mpSound').onchange=e=>e.target.checked?unlock():disarm();document.getElementById('mpStart').onclick=startPhone}
function disarm(){armed=false;audio.pause();audio.currentTime=0;renderPrep()}
async function unlock(){try{audio.muted=true;await audio.play();audio.pause();audio.currentTime=0;audio.muted=false;armed=true}catch{armed=false}renderPrep()}
function startPhone(){if(!armed||started||finished)return;started=true;prep.classList.remove('on');opening.classList.add('on');audio.currentTime=0;audio.play().catch(()=>{started=false;opening.classList.remove('on');prep.classList.add('on');armed=false;renderPrep()})}
function finish(){if(finished)return;finished=true;started=false;audio.pause();opening.classList.remove('on');prep.classList.remove('on');window.dispatchEvent(new CustomEvent('mosaico-opening-finished'))}
document.getElementById('mpPlay').onclick=async()=>{if(finished)return;if(audio.paused){try{await audio.play();mpPlay.textContent='Ⅱ';mpPlay.title='Pausar';mpPlay.setAttribute('aria-label','Pausar')}catch{}}else{audio.pause();mpPlay.textContent='▶';mpPlay.title='Continuar';mpPlay.setAttribute('aria-label','Continuar')}};
document.getElementById('mpRestart').onclick=async()=>{if(finished)return;audio.currentTime=0;try{await audio.play();mpPlay.textContent='Ⅱ';mpPlay.title='Pausar';mpPlay.setAttribute('aria-label','Pausar')}catch{}};
document.getElementById('mpSkip').onclick=finish;
audio.onended=()=>setTimeout(()=>{if(audio.ended)finish()},900);
function show(){if(shown||finished)return;shown=true;renderPrep();prep.classList.add('on')}
window.MosaicoOpening={show,finish};
})();