/* MOSAICO · preparação audiovisual da reunião · Mestre */
(function(){
const IMG='AberturaCelular.jpg',AUDIO='Amanha-do-carroforte.mp3',TELAO_BASE='https://drmarionascimento.github.io/Dragon/carro-forte-noite/telao.html';let armed=false,shown=false,roomCode='',target='phone',fb=null,unsub=null;
const FIREBASE_CONFIG={apiKey:'AIzaSyA160bkgHBrYBwvIxlENax-aAyLWPMaOU4',authDomain:'mosaico-noite.firebaseapp.com',projectId:'mosaico-noite',storageBucket:'mosaico-noite.firebasestorage.app',messagingSenderId:'703343424116',appId:'1:703343424116:web:e6990b5c00d43aca6e9721'};
const css=document.createElement('style');css.textContent=`#mosaicoPrep,#mosaicoOpening{position:fixed;inset:0;z-index:100020;background:#02070bf2;color:#eef5f2;font-family:Inter,system-ui,sans-serif;display:none;overflow:auto}#mosaicoPrep.on,#mosaicoOpening.on{display:flex}.mp-card{width:min(560px,calc(100% - 28px));margin:auto;padding:18px;border:1px solid #3d5360;border-radius:14px;background:linear-gradient(160deg,#13212b,#071016);box-shadow:0 8px 0 #020507,0 28px 70px #000b}.mp-card h2{font:600 30px Georgia,serif;margin:0 0 8px;color:#efc878}.mp-card p{color:#aab9c1;line-height:1.45}.mp-choice,.mp-start{width:100%;min-height:54px;margin-top:10px;padding:12px 14px;border-radius:10px;text-align:left;font-weight:800}.mp-choice{border:1px solid #405866;background:#101d25;color:#eaf2f5;box-shadow:0 4px 0 #020507}.mp-choice b,.mp-choice span{display:block}.mp-choice span{font-size:12px;color:#9fb0b8;margin-top:4px}.mp-choice.selected{border-color:#e8a94a;background:#2a2012}.mp-start{border:0;background:linear-gradient(#ffc266,#dd8b2e);color:#1b1005;text-align:center;box-shadow:0 5px 0 #6a3712}.mp-start:disabled{opacity:.38}.mp-note{margin-top:12px;padding:10px;border-left:3px solid #70d6a0;background:#0b1c16;color:#b8d7c7}.mp-qr{display:none;margin-top:14px;padding:14px;background:#fff;border-radius:12px;text-align:center;color:#081018}.mp-qr.on{display:block}.mp-qr svg{display:block;width:min(280px,72vw);height:auto;margin:auto}.mp-qr b{display:block;margin-top:8px;font:800 16px monospace}.opening-stage{position:relative;width:100%;height:100%;overflow:hidden;background:#020609;display:grid;place-items:center}.opening-stage img{width:100%;height:100%;object-fit:contain;background:#020609}.opening-controls{position:absolute;left:50%;bottom:max(18px,env(safe-area-inset-bottom));transform:translateX(-50%);display:flex;gap:8px;padding:8px;background:#050b12d9;border:1px solid #415765;border-radius:12px}.opening-controls button{min-height:44px;border:1px solid #506976;border-radius:8px;background:#10202a;color:#eef5f2;padding:8px 13px;font-weight:800}`;document.head.appendChild(css);
const prep=document.createElement('div');prep.id='mosaicoPrep';prep.innerHTML=`<div class="mp-card"><h2>📓 PREPARAR A REUNIÃO</h2><div id="mpState"></div></div>`;document.body.appendChild(prep);const stateBox=prep.querySelector('#mpState');
const opening=document.createElement('div');opening.id='mosaicoOpening';opening.innerHTML=`<div class="opening-stage"><img src="${IMG}" alt="Abertura de A Manhã do Carro-Forte"><audio id="mpAudio" preload="auto" src="${AUDIO}"></audio><div class="opening-controls"><button id="mpPlay">⏸ Pausar</button><button id="mpRestart">↻ Reiniciar</button><button id="mpSkip">Pular abertura</button></div></div>`;document.body.appendChild(opening);const audio=opening.querySelector('#mpAudio');
function detectCode(){const t=document.querySelector('.dr-sala-code')?.textContent||document.querySelector('.dr-code')?.textContent||new URLSearchParams(location.search).get('sala')||'';const m=t.toUpperCase().match(/[A-Z2-9]{6}/);if(m)roomCode=m[0]}
function telaoUrl(){detectCode();if(!roomCode)return'';const u=new URL(TELAO_BASE);u.searchParams.set('sala',roomCode);u.searchParams.set('telao','1');u.searchParams.set('v',Date.now().toString());return u.toString()}
async function initFirebase(){if(fb)return fb;const appmod=await import('https://www.gstatic.com/firebasejs/10.12.5/firebase-app.js'),fs=await import('https://www.gstatic.com/firebasejs/10.12.5/firebase-firestore.js');const app=appmod.getApps().find(a=>a.name==='dragon-opening-master')||appmod.initializeApp(FIREBASE_CONFIG,'dragon-opening-master');fb={db:fs.getFirestore(app),doc:fs.doc,setDoc:fs.setDoc,onSnapshot:fs.onSnapshot,serverTimestamp:fs.serverTimestamp};return fb}
async function displayRef(){detectCode();if(!roomCode)throw new Error('Código da sala não localizado.');const f=await initFirebase();return f.doc(f.db,'noite',roomCode,'sistema','abertura')}
function renderChoice(){target='phone';stateBox.innerHTML=`<p>Os jogadores já estão na sala. Escolha onde a abertura pública será apresentada.</p><button class="mp-choice" id="mpSound"><b>🔊 Entendi · ativar som</b><span>Use se a narração tocar neste aparelho.</span></button><button class="mp-choice selected" id="mpPhone"><b>📱 Neste aparelho</b><span>Imagem e áudio no aparelho do Mestre.</span></button><button class="mp-choice" id="mpDisplay"><b>📺 Conectar Telão</b><span>Conecta o dispositivo ligado ao projetor.</span></button><div class="mp-note">📱 Abertura configurada para este aparelho.</div><button class="mp-start" id="mpStart" disabled>▶ INICIAR ABERTURA</button>`;mpSound.onclick=unlock;mpPhone.onclick=renderChoice;mpDisplay.onclick=renderQR;mpStart.onclick=startPhone}
async function unlock(){try{audio.muted=true;await audio.play();audio.pause();audio.currentTime=0;audio.muted=false}catch{}armed=true;renderChoice();mpSound.classList.add('selected');mpSound.querySelector('span').textContent='Som ativado ✓';mpStart.disabled=false}
async function renderQR(){target='display';const url=telaoUrl();if(!url){stateBox.innerHTML='<p>📺 Código da sala não localizado. Reabra Sala e confirme o código.</p><button class="mp-choice" id="mpBack">← Voltar</button>';mpBack.onclick=renderChoice;return}stateBox.innerHTML=`<p><b>📺 Conectar Telão</b></p><p>Escaneie este QR no dispositivo ligado ao projetor.</p><div class="mp-qr on" id="mpTelaoQR"></div><div class="mp-note" id="mpStatus">Aguardando o Telão ativar o áudio…</div><button class="mp-choice" id="mpBack">← Voltar</button>`;mpTelaoQR.innerHTML=(window.MosaicoQR?window.MosaicoQR.svg(url,{nivel:'M',margem:4,rotulo:'QR exclusivo do Telão'}):`<p>${url}</p>`)+`<b>SALA ${roomCode} · TELÃO</b>`;mpBack.onclick=()=>{unsub?.();unsub=null;renderChoice()};try{const f=await initFirebase(),r=await displayRef();await f.setDoc(r,{status:'waiting',command:'idle',updatedAt:f.serverTimestamp()},{merge:true});unsub?.();unsub=f.onSnapshot(r,s=>{const d=s.exists()?s.data():{};if(d.status==='ready')renderReady()})}catch(e){mpStatus.textContent='Não foi possível sincronizar o Telão: '+e.message}}
function renderReady(){target='display';unsub?.();unsub=null;stateBox.innerHTML=`<p><b>📺 Telão conectado ✓</b></p><div class="mp-note">Áudio preparado no dispositivo de projeção.</div><button class="mp-start" id="mpStartDisplay">▶ INICIAR ABERTURA NO TELÃO</button><button class="mp-choice" id="mpBack">← Voltar</button>`;mpStartDisplay.onclick=startDisplay;mpBack.onclick=renderChoice}
async function startDisplay(){try{const f=await initFirebase(),r=await displayRef(),token=Date.now();await f.setDoc(r,{status:'ready',command:'start',token,updatedAt:f.serverTimestamp()},{merge:true});stateBox.innerHTML='<p><b>▶ Abertura em andamento no Telão</b></p><div class="mp-note">Aguarde o término da narração.</div>';unsub?.();unsub=f.onSnapshot(r,s=>{const d=s.exists()?s.data():{};if(d.status==='finished'&&d.finishedToken===token){unsub?.();unsub=null;finish()}})}catch(e){stateBox.innerHTML=`<p>Falha ao iniciar no Telão: ${e.message}</p><button class="mp-choice" id="mpBack">← Voltar</button>`;mpBack.onclick=renderReady}}
function startPhone(){if(!armed)return;prep.classList.remove('on');opening.classList.add('on');audio.currentTime=0;audio.play().catch(()=>{opening.classList.remove('on');prep.classList.add('on');renderChoice()})}
function finish(){audio.pause();opening.classList.remove('on');prep.classList.remove('on');window.dispatchEvent(new CustomEvent('mosaico-opening-finished'))}
opening.querySelector('#mpPlay').onclick=()=>{if(audio.paused){audio.play();mpPlay.textContent='⏸ Pausar'}else{audio.pause();mpPlay.textContent='▶ Continuar'}};opening.querySelector('#mpRestart').onclick=()=>{audio.currentTime=0;audio.play();mpPlay.textContent='⏸ Pausar'};opening.querySelector('#mpSkip').onclick=finish;audio.onended=()=>setTimeout(finish,900);
function showPrep(){if(shown)return;shown=true;detectCode();renderChoice();prep.classList.add('on')}
document.addEventListener('click',e=>{const close=e.target.closest?.('#dragonSalaPanel .dr-close');if(close&&document.getElementById('dragonSalaBtn'))setTimeout(showPrep,80)},true);if(new URLSearchParams(location.search).get('soloLab')==='1')document.addEventListener('click',e=>{if(e.target.closest?.('#enterBtn'))setTimeout(showPrep,120)},true);window.MosaicoOpening={show:showPrep,finish};
})();