/* MOSAICO · preparação audiovisual da reunião */
(function(){
const IMG='Abertura.jpg',AUDIO='Amanha-do-carroforte.mp3';let armed=false,shown=false,roomCode='';
const css=document.createElement('style');css.textContent=`#mosaicoPrep,#mosaicoOpening{position:fixed;inset:0;z-index:100020;background:#02070bd9;color:#eef5f2;font-family:Inter,system-ui,sans-serif;display:none}#mosaicoPrep.on,#mosaicoOpening.on{display:flex}.mp-card{width:min(560px,calc(100% - 28px));margin:auto;padding:18px;border:1px solid #3d5360;border-radius:14px;background:linear-gradient(160deg,#13212b,#071016);box-shadow:0 8px 0 #020507,0 28px 70px #000b}.mp-card h2{font:600 30px Georgia,serif;margin:0 0 8px;color:#efc878}.mp-card p{color:#aab9c1;line-height:1.45}.mp-choice,.mp-start{width:100%;min-height:54px;margin-top:10px;padding:12px 14px;border-radius:10px;text-align:left;font-weight:800}.mp-choice{border:1px solid #405866;background:#101d25;color:#eaf2f5;box-shadow:0 4px 0 #020507}.mp-choice b,.mp-choice span{display:block}.mp-choice span{font-size:12px;color:#9fb0b8;margin-top:4px}.mp-choice.selected{border-color:#e8a94a;background:#2a2012}.mp-start{border:0;background:linear-gradient(#ffc266,#dd8b2e);color:#1b1005;text-align:center;box-shadow:0 5px 0 #6a3712}.mp-start:disabled{opacity:.4}.mp-note{margin-top:12px;padding:10px;border-left:3px solid #70d6a0;background:#0b1c16;color:#b8d7c7}.opening-stage{position:relative;width:100%;height:100%;overflow:hidden;background:#020609;display:grid;place-items:center}.opening-stage img{width:100%;height:100%;object-fit:contain;background:#020609}.opening-controls{position:absolute;left:50%;bottom:max(18px,env(safe-area-inset-bottom));transform:translateX(-50%);display:flex;gap:8px;padding:8px;background:#050b12d9;border:1px solid #415765;border-radius:12px}.opening-controls button{min-height:44px;border:1px solid #506976;border-radius:8px;background:#10202a;color:#eef5f2;padding:8px 13px;font-weight:800}`;document.head.appendChild(css);
const prep=document.createElement('div');prep.id='mosaicoPrep';prep.innerHTML=`<div class="mp-card"><h2>📓 PREPARAR A REUNIÃO</h2><p>Os jogadores já estão na sala. Agora escolha onde a abertura pública será apresentada.</p><button class="mp-choice" id="mpSound"><b>🔊 Entendi · ativar som</b><span>Libera a reprodução da narração neste navegador.</span></button><button class="mp-choice selected" id="mpPhone"><b>📱 Neste aparelho</b><span>Imagem e áudio no aparelho do Mestre.</span></button><button class="mp-choice" id="mpDisplay"><b>📺 Conectar Telão</b><span>Abre a exibição pública da sala para projeção.</span></button><div id="mpStatus" class="mp-note">📱 Abertura configurada para este aparelho.</div><button class="mp-start" id="mpStart" disabled>▶ INICIAR ABERTURA</button></div>`;document.body.appendChild(prep);
const opening=document.createElement('div');opening.id='mosaicoOpening';opening.innerHTML=`<div class="opening-stage"><img src="${IMG}" alt="Abertura de A Manhã do Carro-Forte"><audio id="mpAudio" preload="auto" src="${AUDIO}"></audio><div class="opening-controls"><button id="mpPlay">⏸ Pausar</button><button id="mpRestart">↻ Reiniciar</button><button id="mpSkip">Pular abertura</button></div></div>`;document.body.appendChild(opening);
const audio=opening.querySelector('#mpAudio');let target='phone';
function detectCode(){const t=document.querySelector('.dr-sala-code')?.textContent||document.querySelector('.dr-code')?.textContent||new URLSearchParams(location.search).get('sala')||'';const m=t.toUpperCase().match(/[A-Z2-9]{6}/);if(m)roomCode=m[0];}
async function unlock(){try{audio.muted=true;await audio.play();audio.pause();audio.currentTime=0;audio.muted=false;armed=true;mpSound.classList.add('selected');mpSound.querySelector('span').textContent='Som ativado ✓';mpStart.disabled=false}catch{armed=true;mpSound.classList.add('selected');mpStart.disabled=false}}
function select(which){target=which;mpPhone.classList.toggle('selected',which==='phone');mpDisplay.classList.toggle('selected',which==='display');if(which==='phone')mpStatus.textContent='📱 Abertura configurada para este aparelho.';else{detectCode();mpStatus.textContent=roomCode?'📺 Telão preparado para a sala '+roomCode+'. Abra-o e ative o som na tela de projeção.':'📺 Abra o Telão pelo fluxo da sala e ative o som na projeção.'}}
function finish(){audio.pause();opening.classList.remove('on');prep.classList.remove('on');window.dispatchEvent(new CustomEvent('mosaico-opening-finished'))}
function start(){if(!armed)return;if(target==='display'){detectCode();if(roomCode){window.open(`telao.html?sala=${encodeURIComponent(roomCode)}&abertura=1`,'mosaico-telao');mpStatus.textContent='📺 Telão aberto. Ative o som e inicie a abertura na tela de projeção.';return}mpStatus.textContent='📺 Código da sala não localizado. Abra o Telão pelo botão Sala.';return}prep.classList.remove('on');opening.classList.add('on');audio.currentTime=0;audio.play().catch(()=>{opening.classList.remove('on');prep.classList.add('on');mpStatus.textContent='🔊 O navegador bloqueou o áudio. Toque novamente em Entendi · ativar som.'})}
mpSound.onclick=unlock;mpPhone.onclick=()=>select('phone');mpDisplay.onclick=()=>select('display');mpStart.onclick=start;mpPlay.onclick=()=>{if(audio.paused){audio.play();mpPlay.textContent='⏸ Pausar'}else{audio.pause();mpPlay.textContent='▶ Continuar'}};mpRestart.onclick=()=>{audio.currentTime=0;audio.play();mpPlay.textContent='⏸ Pausar'};mpSkip.onclick=finish;audio.onended=()=>setTimeout(finish,900);
function showPrep(){if(shown)return;shown=true;detectCode();prep.classList.add('on')}
/* O QR continua sendo a primeira etapa. Quando o Mestre fecha o painel Sala pela primeira vez, entra a preparação audiovisual. */
document.addEventListener('click',e=>{const close=e.target.closest?.('#dragonSalaPanel .dr-close');if(close&&document.getElementById('dragonSalaBtn'))setTimeout(showPrep,80)},true);
/* Ensaio solo não possui QR; oferece a preparação após entrar na reunião. */
if(new URLSearchParams(location.search).get('soloLab')==='1'){document.addEventListener('click',e=>{if(e.target.closest?.('#enterBtn'))setTimeout(showPrep,120)},true)}
window.MosaicoOpening={show:showPrep,start,finish};
})();