/* MOSAICO — Solo Lab bots. Camada isolada do núcleo multiplayer. */
(function(){if(new URLSearchParams(location.search).get('soloLab')!=='1')return;
const BOTS=[{slot:2,name:'Bot Analítico',profile:'analítico',coins:12,fragments:3,actions:0,hypothesis:'em aberto',decision:[.72,.90]},{slot:3,name:'Bot Cauteloso',profile:'cauteloso',coins:12,fragments:3,actions:0,hypothesis:'em aberto',decision:[.78,.94]},{slot:4,name:'Bot Intuitivo',profile:'intuitivo',coins:12,fragments:3,actions:0,hypothesis:'em aberto',decision:[.48,.72]},{slot:5,name:'Bot Impulsivo',profile:'impulsivo',coins:12,fragments:3,actions:0,hypothesis:'em aberto',decision:[.20,.45]},{slot:6,name:'Bot Documental',profile:'documental',coins:12,fragments:3,actions:0,hypothesis:'em aberto',decision:[.70,.90]},{slot:7,name:'Bot Explorador',profile:'explorador',coins:12,fragments:3,actions:0,hypothesis:'em aberto',decision:[.42,.70]},{slot:8,name:'Bot Revisionista',profile:'revisionista',coins:12,fragments:3,actions:0,hypothesis:'em aberto',decision:[.75,.95]}];
const LAB=window.MosaicoSoloBots={active:true,bots:BOTS,events:[],log(type,data={}){this.events.push({at:Date.now(),type,...data})}};let activeSlot=0,armed=false,acted=false,startSeconds=0,targetElapsed=0,lastLeft=null,serial=0;
const slotFrom=s=>{const m=/^Arquivo\s+(\d+)$/i.exec(s||'');return m?+m[1]:0},seconds=()=>{const m=/(\d+):(\d+)/.exec(document.getElementById('turnTimer')?.textContent||'');return m?(+m[1]*60)+(+m[2]):0},botFor=s=>BOTS.find(b=>b.slot===s);
function update(bot){const card=[...document.querySelectorAll('#opponents .opponent')][bot.slot-2];if(!card)return;card.querySelector('b').textContent=bot.name;card.querySelector('span').textContent=`${bot.fragments} fragmentos · ${bot.hypothesis}`}
function choose(b){const r=Math.random();if((b.profile==='analítico'||b.profile==='documental')&&b.coins>=4&&r<.55)return'buy';if(b.profile==='cauteloso')return b.coins>=4&&r<.65?'buy':'observe';if(b.profile==='impulsivo')return b.coins>=3&&r<.7?'risk':b.coins>=2?'capture':'observe';if(b.profile==='explorador')return b.coins>=2&&r<.55?'capture':b.coins>=4?'buy':'observe';if(b.profile==='revisionista')return b.actions>1&&b.coins>=3?'risk':b.coins>=4?'buy':'observe';if(b.profile==='intuitivo')return b.coins>=3&&r<.55?'risk':b.coins>=4?'buy':'observe';return b.coins>=3?'risk':'observe'}
function act(b,elapsed){const core=window.MosaicoCore,kind=choose(b),snap=core?.getSnapshot();let label='observou',result=null;if(kind==='buy'&&b.coins>=4){result=core?.solo.buy(b.slot);if(result){b.coins-=4;b.fragments++;label=`comprou ${result}`}}else if(kind==='capture'&&b.coins>=2){const targets=BOTS.filter(x=>x.slot!==b.slot&&x.fragments>0);const target=targets[Math.floor(Math.random()*targets.length)];if(target&&core?.solo.capture(b.slot,target.slot)){b.coins-=2;b.fragments++;target.fragments=Math.max(0,target.fragments-1);update(target);label=`capturou de ${target.name}`}}else if(kind==='risk'&&b.coins>=3&&snap){const open=snap.answers.map((_,i)=>i).filter(i=>!snap.locked.includes(i));if(open.length){const field=open[Math.floor(Math.random()*open.length)],skill={analítico:.78,documental:.75,cauteloso:.68,revisionista:.72,intuitivo:.58,explorador:.55,impulsivo:.42}[b.profile]||.55,correct=Math.random()<skill;result=core.solo.risk(b.slot,field,correct);b.coins-=3;if(result==='locked'){b.coins+=3;b.hypothesis='campo confirmado';label=`travou o campo ${field+1}`}else{b.hypothesis='hipótese falhou';label=`errou o campo ${field+1}`}}}b.actions++;update(b);LAB.log('bot-action',{serial,slot:b.slot,bot:b.name,action:label,result,elapsed,hand:startSeconds})}
function arm(b,left){activeSlot=b.slot;armed=true;acted=false;startSeconds=left;lastLeft=left;serial++;const[a,z]=b.decision;targetElapsed=Math.max(1,Math.round(left*(a+Math.random()*(z-a))));LAB.log('bot-thinking',{serial,bot:b.name,hand:left,targetElapsed})}
function tick(){BOTS.forEach(update);const turn=document.getElementById('turnPlayer')?.textContent.trim()||'',slot=slotFrom(turn),left=seconds(),hud=document.getElementById('hudTurn');if(slot===1){activeSlot=1;armed=false;acted=false;lastLeft=left;if(hud)hud.textContent='Você';return}const b=botFor(slot);if(!b)return;if(hud)hud.textContent=b.name;const valid=left===30||left===60,reset=lastLeft!==null&&left>lastLeft;if(slot!==activeSlot){activeSlot=slot;armed=false;acted=false;lastLeft=left}if(!armed&&(valid||reset))arm(b,left>=46?60:30);if(!armed){lastLeft=left;return}const elapsed=Math.max(0,startSeconds-left);if(!acted&&left>0&&elapsed>=targetElapsed){acted=true;act(b,elapsed)}if(!acted&&left===0){acted=true;LAB.log('bot-timeout',{serial,slot:b.slot,bot:b.name,hand:startSeconds})}lastLeft=left}
setInterval(tick,120);window.addEventListener('pagehide',()=>LAB.active=false);})();