import type {
  CartaTile,
  Character,
  Clue,
  ClueKind,
  MarketLot,
  Option,
  StoryCard,
  CaseTruth,
} from "./types";

export const CHARACTERS: Character[] = [
  {
    id: "tomas",
    seat: 0,
    title: "O Investigador",
    name: "Tomás Vale",
    role: "observador",
    blurb: "Chegou primeiro. Observa paredes como se fossem testemunhas.",
    arrival: "O primeiro carro. Os faróis cortaram a névoa — e ela fechou de novo.",
  },
  {
    id: "helena",
    seat: 1,
    title: "A Herdeira",
    name: "Helena Costa",
    role: "neutro",
    blurb: "A casa deveria ser dela ao amanhecer. A trava do cofre já estava marcada.",
    arrival: "Surgiu da névoa ao lado de Tomás, olhando a janela do segundo andar.",
  },
  {
    id: "elias",
    seat: 2,
    title: "O Morador",
    name: "Elias Costa",
    role: "boato",
    blurb: "Entrou sem fazer barulho. A casa parece conhecê-lo de cor.",
    arrival: "A porta nem pareceu abrir. Passos leves, calculados.",
  },
  {
    id: "clara",
    seat: 3,
    title: "A Jornalista",
    name: "Clara Menezes",
    role: "boato",
    blurb: "Segura a bolsa como se o que está dentro pesasse mais que a noite.",
    arrival: "Entrou como quem está atrasada — mesmo não estando.",
  },
  {
    id: "nilo",
    seat: 4,
    title: "O Policial",
    name: "Nilo Andrade",
    role: "observador",
    blurb: "Tenta parecer calmo. O reflexo metálico na janela o denuncia.",
    arrival: "Olhou a tempestade, depois os outros, depois a casa. A casa olhou de volta.",
  },
  {
    id: "iris",
    seat: 5,
    title: "A Menina",
    name: "Íris Viana",
    role: "neutro",
    blurb: "A última a entrar. Viu tudo. Não disse nada.",
    arrival: "Entrou devagar, como quem não quer interromper o que já começou.",
  },
];

export const ROOMS: { id: Clue["room"]; label: string }[] = [
  { id: "sala", label: "Sala" },
  { id: "cofre", label: "Cofre" },
  { id: "corredor", label: "Corredor" },
  { id: "escada", label: "Escada" },
  { id: "sotao", label: "Sótão" },
  { id: "cozinha", label: "Cozinha" },
  { id: "jardim", label: "Jardim interno" },
  { id: "porta", label: "Porta da frente" },
];

export const CLUES: Clue[] = [
  {
    id: "p01a",
    kind: "pilar",
    title: "Óleo na alavanca",
    body: "O disjuntor do serviço, atrás do quarto degrau, tem óleo fresco na alavanca. Não foi a tempestade: alguém baixou à mão.",
    room: "escada",
    pillar: "disjuntor",
    reliability: 3,
    truthful: true,
    mosaicLabel: "Disjuntor baixado à mão",
  },
  {
    id: "p01b",
    kind: "pilar",
    title: "A luz morreu inteira",
    body: "Às 21h29 a luz não piscou: apagou de uma vez. Queda de tempestade oscila. Esta foi um corte.",
    room: "sala",
    pillar: "disjuntor",
    reliability: 3,
    truthful: true,
    mosaicLabel: "Corte seco às 21h29",
  },
  {
    id: "p02a",
    kind: "pilar",
    title: "Segunda marca",
    body: "A trava do cofre tem duas impressões. A de baixo, mais seca. A de cima, mais fundo, feita no escuro.",
    room: "cofre",
    pillar: "cofre-aberto",
    reliability: 3,
    truthful: true,
    mosaicLabel: "Duas marcas no cofre",
  },
  {
    id: "p02b",
    kind: "pilar",
    title: "Objeto metálico",
    body: "No escuro, algo pequeno e metálico caiu na sala — o som veio de dentro do cofre. Depois a luz voltou e o cofre estava aberto um centímetro.",
    room: "cofre",
    pillar: "cofre-aberto",
    reliability: 3,
    truthful: true,
    mosaicLabel: "Metal caiu do cofre",
  },
  {
    id: "p03a",
    kind: "pilar",
    title: "Posições trocadas",
    body: "Quando a luz voltou, ninguém estava onde lembrava estar. Só o suficiente para incomodar. Alguém se moveu com precisão.",
    room: "sala",
    pillar: "movimento",
    reliability: 3,
    truthful: true,
    mosaicLabel: "Deslocamento no escuro",
  },
  {
    id: "p03b",
    kind: "pilar",
    title: "Atrás de Tomás",
    body: "No segundo da escuridão, Tomás ouviu um deslocamento atrás de si — rápido, contido, calculado. Não foi passo. Foi decisão.",
    room: "sala",
    pillar: "movimento",
    reliability: 3,
    truthful: true,
    mosaicLabel: "Movimento atrás do Investigador",
  },
  {
    id: "p04a",
    kind: "pilar",
    title: "Relógio de Helena",
    body: "O relógio de pulso da Herdeira parou em 21h29. O ponteiro não avançou até a luz voltar.",
    room: "sala",
    pillar: "janela-tempo",
    reliability: 3,
    truthful: true,
    mosaicLabel: "21h29 — início do corte",
  },
  {
    id: "p04b",
    kind: "pilar",
    title: "Último sinal",
    body: "O telefone de Clara registrou o último pacote de rede às 21h31. A escuridão durou dois minutos.",
    room: "sala",
    pillar: "janela-tempo",
    reliability: 3,
    truthful: true,
    mosaicLabel: "21h31 — a luz volta",
  },
  {
    id: "p05a",
    kind: "pilar",
    title: "A marca de baixo",
    body: "A impressão mais antiga na trava estava ali antes dos carros chegarem. Borda já seca. Alguém tocou o cofre sozinho.",
    room: "cofre",
    pillar: "antes",
    reliability: 3,
    truthful: true,
    mosaicLabel: "Toque no cofre antes dos convidados",
  },
  {
    id: "p05b",
    kind: "pilar",
    title: "Quem já estava dentro",
    body: "Elias não foi visto chegando. A porta não rangeu. Ele já estava na casa quando o primeiro farol cortou a névoa.",
    room: "porta",
    pillar: "antes",
    reliability: 3,
    truthful: true,
    mosaicLabel: "O Morador já estava dentro",
  },
  {
    id: "p06a",
    kind: "pilar",
    title: "O corredor que cala",
    body: "A madeira do corredor range para Helena, para Tomás, para Nilo. Sob os pés de Elias, a casa segura o som.",
    room: "corredor",
    pillar: "conhecia",
    reliability: 3,
    truthful: true,
    mosaicLabel: "A casa cala para o Morador",
  },
  {
    id: "p06b",
    kind: "pilar",
    title: "Um centímetro na cozinha",
    body: "A porta do armário da cozinha estava aberta um centímetro. Tomás fechou. Ela abriu de novo. Alguém que conhecia o trinco.",
    room: "cozinha",
    pillar: "conhecia",
    reliability: 3,
    truthful: true,
    mosaicLabel: "Armário que reabre sozinho",
  },
  {
    id: "p07a",
    kind: "pilar",
    title: "Silêncio no corredor",
    body: "Durante o apagão, o corredor não rangeu. Quem passou ali era alguém para quem a casa guarda silêncio.",
    room: "corredor",
    pillar: "elias-corredor",
    reliability: 3,
    truthful: true,
    mosaicLabel: "Passagem silenciosa no apagão",
  },
  {
    id: "p07b",
    kind: "pilar",
    title: "A mão fechada",
    body: "Quando a luz voltou, Elias estava com a mão fechada — como quem segura algo. Depois abriu. Não havia nada visível.",
    room: "corredor",
    pillar: "elias-corredor",
    reliability: 3,
    truthful: true,
    mosaicLabel: "Mão fechada do Morador",
  },
  {
    id: "p08a",
    kind: "pilar",
    title: "A porta mais aberta",
    body: "Antes da queda, a porta da sala estava entreaberta. Depois, um pouco mais. Só o suficiente para não ser acidente.",
    room: "sala",
    pillar: "rota-saida",
    reliability: 3,
    truthful: true,
    mosaicLabel: "Porta da sala cedeu passagem",
  },
  {
    id: "p08b",
    kind: "pilar",
    title: "Pressão na madeira",
    body: "Tomás passou a mão na porta da sala. Um ponto específico estava mais frio, como se alguém tivesse pressionado ali no escuro — rumo à saída.",
    room: "porta",
    pillar: "rota-saida",
    reliability: 3,
    truthful: true,
    mosaicLabel: "Marca de pressão rumo à saída",
  },
  {
    id: "p09a",
    kind: "pilar",
    title: "Arranhão por dentro",
    body: "A fechadura da porta da frente tem um arranhão fresco do lado de dentro. Alguém tentou destrancar com pressa e a madeira inchada não cedeu.",
    room: "porta",
    pillar: "emperrada",
    reliability: 3,
    truthful: true,
    mosaicLabel: "Porta da frente emperrada por dentro",
  },
  {
    id: "p09b",
    kind: "pilar",
    title: "A névoa que entrou e sumiu",
    body: "A névoa entrou pela fresta como se tivesse sido convidada. Depois da queda, tinha desaparecido. A porta abriu — e não fechou direito.",
    room: "porta",
    pillar: "emperrada",
    reliability: 3,
    truthful: true,
    mosaicLabel: "Ciclo da névoa na porta",
  },
  {
    id: "p10a",
    kind: "pilar",
    title: "O que falta no cofre",
    body: "Helena olhou para dentro do centímetro aberto. Não viu um objeto. Viu a ausência: a escritura da Casa da Costa não estava lá.",
    room: "cofre",
    pillar: "motivo",
    reliability: 3,
    truthful: true,
    mosaicLabel: "Escritura ausente",
  },
  {
    id: "p10b",
    kind: "pilar",
    title: "A discussão de antes",
    body: "Antes dos faróis, houve uma discussão curta na sala. Helena: o cartório vem amanhã. Elias: esta casa não muda de mão assim.",
    room: "sala",
    pillar: "motivo",
    reliability: 3,
    truthful: true,
    mosaicLabel: "Briga pela posse da casa",
  },
  {
    id: "p11a",
    kind: "pilar",
    title: "O olhar para o sótão",
    body: "Elias, ao entrar, olhou para a escada, o sótão e o quadro de serviço. Ninguém mais sabia onde a casa guarda a luz.",
    room: "sotao",
    pillar: "painel",
    reliability: 3,
    truthful: true,
    mosaicLabel: "Só o Morador conhece o painel",
  },
  {
    id: "p11b",
    kind: "pilar",
    title: "O quarto degrau",
    body: "O quarto degrau cede um milímetro demais. Por baixo há um alçapão de serviço que leva ao disjuntor. Nilo sentiu com o pé.",
    room: "escada",
    pillar: "painel",
    reliability: 3,
    truthful: true,
    mosaicLabel: "Alçapão no quarto degrau",
  },
  {
    id: "p12a",
    kind: "pilar",
    title: "A chave caída",
    body: "O metal que caiu no escuro é a chave reserva da porta da frente. Sem ela, a fechadura inchada não gira.",
    room: "cofre",
    pillar: "chave",
    reliability: 3,
    truthful: true,
    mosaicLabel: "Chave reserva caída",
  },
  {
    id: "p12b",
    kind: "pilar",
    title: "O vazio do chaveiro",
    body: "Helena viu, no fundo do cofre, o gancho do chaveiro vazio. A reserva da frente deveria estar ali. Não está.",
    room: "cofre",
    pillar: "chave",
    reliability: 3,
    truthful: true,
    mosaicLabel: "Chaveiro vazio no cofre",
  },
  {
    id: "c01",
    kind: "conector",
    title: "Dois minutos, um centímetro",
    body: "Dois minutos no escuro bastam para quem já sabe a combinação. Não bastam para procurar no escuro. Quem abriu, já sabia.",
    room: "cofre",
    reliability: 3,
    truthful: true,
    mosaicLabel: "Quem abriu já sabia a combinação",
  },
  {
    id: "c02",
    kind: "conector",
    title: "Duas camadas de toque",
    body: "A marca seca de baixo e a marca fundo de cima não são o mesmo gesto. Um toque antes da noite. Outro durante o apagão.",
    room: "cofre",
    reliability: 3,
    truthful: true,
    mosaicLabel: "Dois toques, dois momentos",
  },
  {
    id: "c03",
    kind: "conector",
    title: "Água que não é chuva",
    body: "As folhas do jardim interno estão molhadas. Lá não chove. A água é fria, densa, de fundação. Subiu por baixo.",
    room: "jardim",
    reliability: 3,
    truthful: true,
    mosaicLabel: "Água pela fundação",
  },
  {
    id: "c04",
    kind: "conector",
    title: "Cortina sem vento",
    body: "A janela estava trancada. A barra da cortina torta um centímetro: alguém usou o tecido como cobertura, não o vento.",
    room: "sala",
    reliability: 2,
    truthful: true,
    mosaicLabel: "Cortina usada como cobertura",
  },
  {
    id: "c05",
    kind: "conector",
    title: "Degrau, alçapão, luz",
    body: "Quarto degrau → alçapão → disjuntor. Quem conhece a casa apaga a noite inteira em um gesto.",
    room: "escada",
    reliability: 3,
    truthful: true,
    mosaicLabel: "Caminho do apagão",
  },
  {
    id: "c06",
    kind: "conector",
    title: "Punho e ausência",
    body: "Mão fechada de Elias + escritura sumida + chave caída. Três pedaços do mesmo movimento.",
    room: "corredor",
    reliability: 3,
    truthful: true,
    mosaicLabel: "O que a mão levou",
  },
  {
    id: "c07",
    kind: "conector",
    title: "A passagem",
    body: "Porta da sala entreaberta às 21h07. Mais aberta às 21h31. Alguém usou aquele vão como corredor no escuro.",
    room: "sala",
    reliability: 3,
    truthful: true,
    mosaicLabel: "Vão usado como rota",
  },
  {
    id: "c08",
    kind: "conector",
    title: "Névoa de porta",
    body: "Névoa entra, névoa some: a porta da frente abriu durante o apagão e não voltou ao lugar. Emperrou no inchado da tempestade.",
    room: "porta",
    reliability: 3,
    truthful: true,
    mosaicLabel: "Porta abriu e travou",
  },
  {
    id: "k01",
    kind: "contexto",
    title: "Meses sem visita",
    body: "A Casa da Costa não recebia visitas há meses. A poeira, porém, não está na cozinha: alguém manteve o coração da casa.",
    room: "cozinha",
    reliability: 2,
    truthful: true,
    mosaicLabel: "A casa tinha morador",
  },
  {
    id: "k02",
    kind: "contexto",
    title: "A tempestade veio do mar",
    body: "O vento bate como se quisesse entrar. A névoa sobe a encosta como um animal silencioso. Não se move rápido. Se aproxima.",
    room: "porta",
    reliability: 2,
    truthful: true,
    mosaicLabel: "Tempestade de maré",
  },
  {
    id: "k03",
    kind: "contexto",
    title: "Cozinha intacta demais",
    body: "Copos alinhados. Cadeiras no lugar. Sem poeira. Sem uso. Perfeita — e a porta do armário, um centímetro aberta.",
    room: "cozinha",
    reliability: 2,
    truthful: true,
    mosaicLabel: "Cozinha ensaiada",
  },
  {
    id: "k04",
    kind: "contexto",
    title: "Quem convidou?",
    body: "Seis pessoas. Nenhuma confirma ter enviado o recado. A lista parece ter sido escrita por quem já conhecia a ordem de chegada.",
    room: "sala",
    reliability: 2,
    truthful: true,
    mosaicLabel: "Convite sem remetente",
  },
  {
    id: "k05",
    kind: "contexto",
    title: "Folha molhada",
    body: "Íris tocou uma folha do jardim interno. Molhada. Não choveu ali. A gota é fria demais para ser chuva.",
    room: "jardim",
    reliability: 2,
    truthful: true,
    mosaicLabel: "O jardim não deveria estar molhado",
  },
  {
    id: "k06",
    kind: "contexto",
    title: "A casa escolhe a ordem",
    body: "Cada convidado entrou no momento exato em que deveria. Ninguém percebeu quem estava mais perto, atrás, ao lado.",
    room: "porta",
    reliability: 2,
    truthful: true,
    mosaicLabel: "Ordem de chegada ensaiada",
  },
  {
    id: "a01",
    kind: "ambiguidade",
    title: "A sombra pequena",
    body: "No primeiro apagar, uma sombra passou rápido demais. Não era grande. Parecia baixa — do tamanho de Íris, ou de alguém encolhido.",
    room: "corredor",
    reliability: 1,
    truthful: false,
    mosaicLabel: "Sombra do tamanho da Menina",
  },
  {
    id: "a02",
    kind: "ambiguidade",
    title: "A bolsa de Clara",
    body: "Clara segura a bolsa com mais força depois da queda. Algo dentro parece ter peso novo. Ou ela só tem medo de perder o que já era dela.",
    room: "sala",
    reliability: 1,
    truthful: false,
    mosaicLabel: "A bolsa ficou mais pesada",
  },
  {
    id: "a03",
    kind: "ambiguidade",
    title: "Reflexo na janela",
    body: "Nilo viu um traço metálico no vidro, fino, como trajetória. Pode ser a chave. Pode ser o próprio distintivo.",
    room: "sala",
    reliability: 1,
    truthful: false,
    mosaicLabel: "Metal na janela",
  },
  {
    id: "a04",
    kind: "ambiguidade",
    title: "O sótão respira",
    body: "A madeira de cima estala como passo. Pode ser alguém. Pode ser a casa puxando o fio do disjuntor no vão do teto.",
    room: "sotao",
    reliability: 1,
    truthful: false,
    mosaicLabel: "Passos no sótão",
  },
  {
    id: "a05",
    kind: "ambiguidade",
    title: "Helena na trava",
    body: "Vários viram Helena tocar a trava do cofre depois da luz. O toque dela é de quem procura. Não necessariamente de quem abriu.",
    room: "cofre",
    reliability: 1,
    truthful: false,
    mosaicLabel: "A Herdeira tocou o cofre",
  },
  {
    id: "a06",
    kind: "ambiguidade",
    title: "Tomás chegou cedo",
    body: "O Investigador foi o primeiro no portão. Tempo demais sozinho com a casa. Tempo demais para uma marca na trava — se ele a tivesse feito.",
    room: "porta",
    reliability: 1,
    truthful: false,
    mosaicLabel: "O primeiro teve tempo",
  },
  {
    id: "b01",
    kind: "boato",
    title: "Helena ontem à noite",
    body: "Dizem que a Herdeira já esteve na casa ontem, sozinha, e conhece a combinação. Ninguém confirma. Ninguém desmente.",
    room: "sala",
    reliability: 1,
    truthful: false,
    mosaicLabel: "Boato: Helena veio ontem",
  },
  {
    id: "b02",
    kind: "boato",
    title: "O contrato de Tomás",
    body: "Corre que Tomás foi contratado para achar um documento da família Costa — não para a festa. Isso explicaria ele ter chegado primeiro.",
    room: "sala",
    reliability: 1,
    truthful: true,
    mosaicLabel: "Boato: Tomás busca um documento",
  },
  {
    id: "b03",
    kind: "boato",
    title: "Íris não foi convidada",
    body: "Dizem que a Menina entrou porque a casa deixou — filha da antiga caseira, não estava na lista. Verdade pela metade: ela conhece os cômodos.",
    room: "jardim",
    reliability: 1,
    truthful: true,
    mosaicLabel: "Boato: Íris não estava na lista",
  },
  {
    id: "b04",
    kind: "boato",
    title: "Nilo e o desaparecimento",
    body: "Corre que Nilo veio por um desaparecimento antigo nesta costa, não pela noite de hoje. O distintivo seria disfarce.",
    room: "escada",
    reliability: 1,
    truthful: false,
    mosaicLabel: "Boato: Nilo investiga outro caso",
  },
];

export const CLUE_BY_ID: Record<string, Clue> = Object.fromEntries(
  CLUES.map((c) => [c.id, c]),
);

export const STARTING_HANDS: Record<string, string[]> = {
  tomas: ["p03b", "p08b", "p01b", "k01", "c01"],
  helena: ["p02a", "p10a", "p04a", "a01"],
  elias: ["p07b", "p06a", "p05b", "k03", "b01"],
  clara: ["p04b", "a02", "p09b", "k04", "b02"],
  nilo: ["p11b", "p02b", "a03", "p01a", "c05"],
  iris: ["k05", "c03", "p03a", "a04"],
};

export const MARKET_LOTS: MarketLot[] = [
  { id: "r1-pilar-a", round: 1, kind: "pilar", clueId: "p05a" },
  { id: "r1-pilar-b", round: 1, kind: "pilar", clueId: "p10b" },
  { id: "r1-conector", round: 1, kind: "conector", clueId: "c02" },
  { id: "r1-contexto", round: 1, kind: "contexto", clueId: "k02" },
  { id: "r1-amb", round: 1, kind: "ambiguidade", clueId: "a05" },
  { id: "r2-pilar", round: 2, kind: "pilar", clueId: "p09a" },
  { id: "r2-conector-a", round: 2, kind: "conector", clueId: "c06" },
  { id: "r2-conector-b", round: 2, kind: "conector", clueId: "c08" },
  { id: "r2-amb", round: 2, kind: "ambiguidade", clueId: "a06" },
  { id: "r2-contexto", round: 2, kind: "contexto", clueId: "k06" },
];

export const LEFTOVER_BUY: { kind: ClueKind; clueId: string }[] = [
  { kind: "pilar", clueId: "p12a" },
  { kind: "conector", clueId: "c07" },
  { kind: "pilar", clueId: "p11a" },
  { kind: "pilar", clueId: "p08a" },
  { kind: "pilar", clueId: "p06b" },
  { kind: "pilar", clueId: "p07a" },
  { kind: "pilar", clueId: "p12b" },
  { kind: "conector", clueId: "c04" },
];

export const CARTA_TILES: CartaTile[] = [
  { id: "t-marca", label: "Marca no cofre — antes dos convidados", correctIndex: 0 },
  { id: "t-porta", label: "Porta da sala entreaberta — 21h07", correctIndex: 1 },
  { id: "t-disjuntor", label: "Disjuntor desligado à mão — 21h29", correctIndex: 2 },
  { id: "t-cofre", label: "Cofre aberto no escuro", correctIndex: 3 },
  { id: "t-emperra", label: "Porta da frente emperra", correctIndex: 4 },
  { id: "t-agua", label: "Água sobe pela fundação", correctIndex: 5 },
  { id: "t-iris", label: "Íris abre o jardim para a névoa", correctIndex: null },
  { id: "t-storm", label: "A tempestade derruba a luz sozinha", correctIndex: null },
  { id: "t-helena", label: "Helena esvazia o cofre à vista de todos", correctIndex: null },
  { id: "t-sotao", label: "Alguém sobe ao sótão e some", correctIndex: null },
];

export const STORY: Record<string, StoryCard[]> = {
  tomas: [
    {
      id: "s-t0",
      kicker: "21h03",
      text: "A tempestade chegou antes dos convidados. Você desce do primeiro carro. A casa olha de volta. Um som abafado vem do corredor — não é vento, não é madeira.",
    },
    {
      id: "s-t1",
      kicker: "A porta",
      text: "«Tem alguém aí?» Ninguém responde. Ou talvez tenha respondido, e o som se perdeu na tempestade.",
    },
    {
      id: "s-t2",
      kicker: "21h12",
      text: "O cofre está fechado. A marca na trava é recente. Você passa o dedo. Não é sua. «Quem mexeu aqui?»",
    },
  ],
  helena: [
    {
      id: "s-h0",
      kicker: "A névoa",
      text: "Você não entra: você surge. A névoa abre espaço. O vento diminui quando você passa a porta. A janela do segundo andar balança a cortina — fechada.",
    },
    {
      id: "s-h1",
      kicker: "21h07",
      text: "A porta da sala está entreaberta. «Isso não estava assim.» Curto. Direto. O corredor parece ver vocês.",
    },
    {
      id: "s-h2",
      kicker: "O cofre",
      text: "Fechado como deveria. Mas a marca de dedo na trava é fresca. Você toca com o indicador. A casa parece ouvir.",
    },
  ],
  elias: [
    {
      id: "s-e0",
      kicker: "Sem barulho",
      text: "Você chega sem que a porta pareça abrir. Passos leves. A casa observa. Escada, sótão, janela do segundo andar: você já viu o que os outros ainda não viram.",
    },
    {
      id: "s-e1",
      kicker: "A tempestade",
      text: "O vento bate forte quando você passa. Não é aviso para os outros. É para você: o tempo está menor do que o combinado.",
    },
    {
      id: "s-e2",
      kicker: "A mão",
      text: "No bolso, o hábito de fechar os dedos. Há algo que precisa sair desta casa antes do cartório de amanhã.",
    },
  ],
  clara: [
    {
      id: "s-c0",
      kicker: "A bolsa",
      text: "Você entra como quem está atrasada — mesmo não estando. A bolsa pesa. O gravador está desligado. Ainda.",
    },
    {
      id: "s-c1",
      kicker: "A cortina",
      text: "A cortina balança sem vento. A porta, entreaberta. «Quem deixou isso assim?» Ninguém responde. Isso incomoda mais do que deveria.",
    },
    {
      id: "s-c2",
      kicker: "O corredor",
      text: "Por um segundo a luz oscila. Uma sombra passa rápido demais. Você recua sem saber por quê.",
    },
  ],
  nilo: [
    {
      id: "s-n0",
      kicker: "A postura",
      text: "Você entra tentando parecer tranquilo. Olha a tempestade, os outros, a casa. A casa olha de volta. O distintivo pesa no bolso interno.",
    },
    {
      id: "s-n1",
      kicker: "A escada",
      text: "Você sobe dois degraus. Para no terceiro. O som vem do sótão — calculado. Você desce. «Não vou lá.»",
    },
    {
      id: "s-n2",
      kicker: "O reflexo",
      text: "Um traço metálico na janela. «Vocês viram isso?» Ninguém admite. Todos sentem.",
    },
  ],
  iris: [
    {
      id: "s-i0",
      kicker: "A última",
      text: "Você é a última. Sempre a última. Entra devagar. A casa parecia esperar. Teto, sótão, escada, cofre, porta entreaberta. Você vê tudo. Não diz nada.",
    },
    {
      id: "s-i1",
      kicker: "O jardim",
      text: "No jardim interno a tempestade não deveria alcançar. Mesmo assim a névoa está ali. Você toca uma folha. «Não choveu aqui.» Mas a folha está molhada.",
    },
    {
      id: "s-i2",
      kicker: "O silêncio",
      text: "Seu silêncio é mais pesado que qualquer fala. A casa não está recebendo visitas. A casa está escolhendo testemunhas.",
    },
  ],
};

export const SUSPECTS: Option[] = CHARACTERS.map((c) => ({
  id: c.id,
  label: `${c.title} — ${c.name}`,
  hint: c.blurb,
}));

export const MOTIVES: Option[] = [
  {
    id: "m-heranca",
    label: "Tomar a escritura antes do cartório",
    hint: "A casa mudaria de mão ao amanhecer.",
  },
  {
    id: "m-reportagem",
    label: "Publicar a história da família Costa",
    hint: "Uma bolsa, um gravador, um prazo.",
  },
  {
    id: "m-medo",
    label: "Proteger alguém da casa",
    hint: "Medo disfarçado de dever.",
  },
  {
    id: "m-vinganca",
    label: "Acertar uma conta antiga com a família",
    hint: "A costa guarda rancor.",
  },
  {
    id: "m-acidente",
    label: "Não houve intenção — só a tempestade",
    hint: "O vento como único culpado.",
  },
  {
    id: "m-ritual",
    label: "Acordar o que mora na casa",
    hint: "Convites sem remetente.",
  },
];

export const ACTIONS: Option[] = [
  {
    id: "a-disjuntor",
    label: "Desligou o disjuntor e abriu o cofre no escuro",
    hint: "Dois minutos. Um gesto de quem já sabia.",
  },
  {
    id: "a-helena-cofre",
    label: "A Herdeira abriu o cofre à vista de todos",
    hint: "Depois da luz, o toque na trava.",
  },
  {
    id: "a-sotao",
    label: "Alguém subiu ao sótão e sabotou a fiação",
    hint: "Os estalos de cima.",
  },
  {
    id: "a-clara",
    label: "A Jornalista levou o conteúdo na bolsa",
    hint: "O peso que aumentou.",
  },
  {
    id: "a-nilo",
    label: "O Policial forçou a porta da frente",
    hint: "O reflexo metálico.",
  },
  {
    id: "a-iris",
    label: "A Menina deixou a névoa — e a água — entrar",
    hint: "A folha que não deveria estar molhada.",
  },
];

export const PROOFS: Option[] = [
  {
    id: "pr-marcas",
    label: "As duas marcas na trava e o metal caído do cofre",
    hint: "Antes e durante. Mesma mão.",
  },
  {
    id: "pr-bolsa",
    label: "A bolsa de Clara depois da queda",
    hint: "Peso novo, ou medo novo.",
  },
  {
    id: "pr-relogio",
    label: "Só o relógio parado de Helena",
    hint: "Marca a hora, não a mão.",
  },
  {
    id: "pr-sombra",
    label: "A sombra baixa no corredor",
    hint: "Tamanho não é identidade.",
  },
  {
    id: "pr-distintivo",
    label: "O reflexo do distintivo na janela",
    hint: "Metal que já estava no bolso.",
  },
  {
    id: "pr-convite",
    label: "A lista de convidados sem remetente",
    hint: "Explica a mesa, não o cofre.",
  },
];

export const GAPS: Option[] = [
  {
    id: "g-agua-porta",
    label: "Por que a água no jardim e a porta emperrada",
    hint: "A fuga que não completou.",
  },
  {
    id: "g-sotao",
    label: "Quem estava no sótão",
    hint: "Pode ser fiação, não pessoa.",
  },
  {
    id: "g-iris",
    label: "Como Íris entrou sem convite",
    hint: "Explica a menina, não a noite.",
  },
  {
    id: "g-tomas",
    label: "O que Tomás fez sozinho no portão",
    hint: "Tempo não é prova.",
  },
  {
    id: "g-luz",
    label: "Por que a luz voltou sozinha",
    hint: "O disjuntor tem mola de segurança.",
  },
  {
    id: "g-lista",
    label: "Quem escreveu a lista",
    hint: "A casa, ou o morador.",
  },
];

export const EXPLANATIONS: Option[] = [
  {
    id: "x-elias",
    label: "O Morador usou o apagão para levar a escritura e sair — e a casa não deixou.",
  },
  {
    id: "x-helena",
    label: "A Herdeira antecipou o cartório e abriu o que já era dela.",
  },
  {
    id: "x-clara",
    label: "A Jornalista fabricou o apagão para um furo de reportagem.",
  },
  {
    id: "x-tempestade",
    label: "A tempestade fez tudo: luz, cofre, água. Ninguém agiu.",
  },
  {
    id: "x-casa",
    label: "A casa escolheu as testemunhas e moveu os objetos sozinha.",
  },
  {
    id: "x-nilo",
    label: "O Policial encobriu um desaparecimento antigo usando esta noite.",
  },
];

export const TRUTH: CaseTruth = {
  suspectId: "elias",
  motiveId: "m-heranca",
  actionId: "a-disjuntor",
  proofId: "pr-marcas",
  gapId: "g-agua-porta",
  usedClueIds: ["p01a", "p02a", "p02b", "p05a", "p09a", "p10a", "c03", "c05"],
};

export const KIND_LABEL: Record<ClueKind, string> = {
  pilar: "Pista-pilar",
  conector: "Conector",
  contexto: "Contexto",
  ambiguidade: "Ambiguidade",
  boato: "Boato",
};

export const ROLE_LABEL: Record<Character["role"], string> = {
  observador: "Observador",
  boato: "Papel com boatos",
  neutro: "Neutro",
};

export const REVEAL_SLIDES: { kicker: string; title: string; body: string }[] = [
  {
    kicker: "Reconstrução",
    title: "A linha da verdade",
    body: "21h03 a luz avisa. 21h07 a porta da sala entreaberta. 21h12 o cofre fechado com marca fresca — feita antes dos faróis. 21h29 a luz morre de uma vez. 21h31 volta. O cofre está aberto um centímetro. A porta da frente, a meio caminho de uma fuga.",
  },
  {
    kicker: "Ação oculta",
    title: "Dois minutos no escuro",
    body: "Elias Costa já estava na casa. Conhecia o quarto degrau, o alçapão, o disjuntor. Baixou a alavanca à mão. No escuro, abriu o cofre que tinha tocado sozinho à tarde. Levou a escritura. A chave reserva caiu. Ele tentou a porta da frente. A madeira inchada não cedeu.",
  },
  {
    kicker: "Motivo",
    title: "Antes do cartório",
    body: "Helena tomaria a casa ao amanhecer. Elias viveu ali como morador — e recusou a troca de mãos. A discussão foi curta. A decisão, não. Ele queria o papel, a saída, o mar. Não contava com a tempestade virar o que virou.",
  },
  {
    kicker: "A porta e a água",
    title: "A lacuna",
    body: "A névoa entrou porque a porta abriu. Sumiu porque a porta emperrou. A água no jardim interno não é chuva: subiu pela fundação, fria, densa, enquanto seis pessoas ainda tentavam entender o centímetro do cofre.",
  },
  {
    kicker: "Pilares",
    title: "Por que o caso era solucionável",
    body: "Cada pilar tinha duas rotas. O disjuntor: óleo na alavanca e o corte seco. O cofre: segunda marca e o metal caído. A janela de dois minutos: relógio de Helena e sinal de Clara. Ninguém precisava de todas as peças. Precisava de um caminho.",
  },
  {
    kicker: "Ambiguidades",
    title: "O que enganou a mesa",
    body: "A sombra baixa apontava Íris. A bolsa, Clara. O reflexo, Nilo. O sótão, um intruso. Helena na trava, a herdeira. Tomás no portão, o primeiro. Nenhuma dessas rotas abre o cofre no escuro. Todas ocupam a atenção.",
  },
  {
    kicker: "Epílogo",
    title: "A casa está habitada",
    body: "Não por um estranho. Por eles. Em noites em que ninguém junta as peças, a névoa sobe de novo e os faróis cortam o portão. Nesta, alguém pode dizer em voz alta: foi o Morador, foi o cofre, foi a porta, foi a água. A manhã, então, tem permissão para chegar.",
  },
];
