import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js';
import { OrbitControls } from 'https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/controls/OrbitControls.js';

const canvas=document.getElementById('scene');
const stage=document.getElementById('stage');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));
renderer.outputColorSpace=THREE.SRGBColorSpace;
renderer.toneMapping=THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure=1.05;
renderer.shadowMap.enabled=true;
renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();
scene.fog=new THREE.FogExp2(0x120c09,.035);
const camera=new THREE.PerspectiveCamera(38,1,.01,100);
camera.position.set(0,1.1,7.2);
const controls=new OrbitControls(camera,renderer.domElement);
controls.enableDamping=true; controls.dampingFactor=.055; controls.minDistance=2.3; controls.maxDistance=12; controls.target.set(0,0,0);

scene.add(new THREE.HemisphereLight(0xffddbb,0x24140f,2.1));
const key=new THREE.DirectionalLight(0xffc796,4.0);key.position.set(4,6,5);key.castShadow=true;scene.add(key);
const rim=new THREE.DirectionalLight(0xff5a40,2.1);rim.position.set(-5,1,-4);scene.add(rim);
const fill=new THREE.PointLight(0xffe2bd,2.2,18);fill.position.set(-2,2,4);scene.add(fill);

const root=new THREE.Group();scene.add(root);
const pedestal=new THREE.Mesh(new THREE.CylinderGeometry(2.3,2.5,.12,72),new THREE.MeshStandardMaterial({color:0x1d1410,roughness:.78,metalness:.08}));
pedestal.position.y=-1.62;pedestal.receiveShadow=true;scene.add(pedestal);

const mats={muscle:new THREE.MeshPhysicalMaterial({color:0xa92d2d,roughness:.47,metalness:0,clearcoat:.2,clearcoatRoughness:.55}),deep:new THREE.MeshPhysicalMaterial({color:0x7b171c,roughness:.56}),tendon:new THREE.MeshPhysicalMaterial({color:0xe5d2b0,roughness:.72}),fascia:new THREE.MeshPhysicalMaterial({color:0xf1d7c5,roughness:.5,transparent:true,opacity:.34,side:THREE.DoubleSide}),fiber:new THREE.MeshPhysicalMaterial({color:0xc74e4f,roughness:.38}),fiber2:new THREE.MeshPhysicalMaterial({color:0xe07165,roughness:.42}),myo:new THREE.MeshPhysicalMaterial({color:0xb92b3b,roughness:.36}),actin:new THREE.MeshPhysicalMaterial({color:0xe6c657,roughness:.32,metalness:.04}),myosin:new THREE.MeshPhysicalMaterial({color:0x7bb4cf,roughness:.3,metalness:.08}),zline:new THREE.MeshPhysicalMaterial({color:0xf0e5d2,roughness:.45}),dark:new THREE.MeshStandardMaterial({color:0x4a1016,roughness:.5})};

function capsuleBetween(a,b,r,mat,radial=28){const dir=new THREE.Vector3().subVectors(b,a);const len=dir.length();const g=new THREE.CapsuleGeometry(r,Math.max(.001,len-2*r),8,radial);const m=new THREE.Mesh(g,mat);m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),dir.clone().normalize());m.castShadow=true;m.receiveShadow=true;return m}
function tube(points,r,mat,segments=96,radial=18){const c=new THREE.CatmullRomCurve3(points);const m=new THREE.Mesh(new THREE.TubeGeometry(c,segments,r,radial,false),mat);m.castShadow=true;return m}
function labelSprite(text){const c=document.createElement('canvas');c.width=512;c.height=128;const x=c.getContext('2d');x.fillStyle='rgba(12,8,6,.82)';x.roundRect(8,8,496,112,28);x.fill();x.strokeStyle='rgba(243,208,120,.65)';x.lineWidth=3;x.stroke();x.fillStyle='#f6e5bb';x.font='600 34px Inter';x.textAlign='center';x.textBaseline='middle';x.fillText(text,256,64);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthTest:false}));s.scale.set(2.0,.5,1);return s}

function buildMuscle(){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.CapsuleGeometry(1.05,2.55,14,64),mats.muscle);body.rotation.z=Math.PI/2;body.scale.set(1,1.04,.82);body.castShadow=true;g.add(body);const left=capsuleBetween(new THREE.Vector3(-2.8,0,0),new THREE.Vector3(-1.75,0,0),.34,mats.tendon,32);const right=capsuleBetween(new THREE.Vector3(1.75,0,0),new THREE.Vector3(2.8,0,0),.34,mats.tendon,32);g.add(left,right);for(let i=-5;i<=5;i++){const y=i*.14;g.add(tube([new THREE.Vector3(-1.65,y*.42,.72),new THREE.Vector3(0,y,.88),new THREE.Vector3(1.65,y*.42,.72)],.018,mats.deep,64,8))}const lab=labelSprite('Músculo esquelético');lab.position.set(0,1.65,0);g.add(lab);return g}
function buildFascicle(){const g=new THREE.Group();const n=22;for(let i=0;i<n;i++){const a=i*2.399963;const rr=.73*Math.sqrt(i/n);const y=Math.cos(a)*rr;const z=Math.sin(a)*rr;const f=capsuleBetween(new THREE.Vector3(-2.35,y,z),new THREE.Vector3(2.35,y,z),.12,i%3?mats.fiber:mats.fiber2,16);f.rotation.z=Math.PI/2;g.add(f)}const sheath=new THREE.Mesh(new THREE.CylinderGeometry(.92,.92,4.95,64,1,true),mats.fascia);sheath.rotation.z=Math.PI/2;g.add(sheath);const ring=new THREE.Mesh(new THREE.TorusGeometry(.92,.035,12,64),mats.tendon);ring.rotation.y=Math.PI/2;ring.position.x=2.48;g.add(ring);const lab=labelSprite('Fascículo muscular');lab.position.set(0,1.55,0);g.add(lab);return g}
function buildFiber(){const g=new THREE.Group();const cell=new THREE.Mesh(new THREE.CapsuleGeometry(.72,3.4,12,48),mats.fiber);cell.rotation.z=Math.PI/2;cell.scale.z=.9;cell.castShadow=true;g.add(cell);for(let i=0;i<14;i++){const a=i*2.399963;const rr=.46*Math.sqrt((i+1)/14);const y=Math.cos(a)*rr;const z=Math.sin(a)*rr;const m=new THREE.Mesh(new THREE.CylinderGeometry(.055,.055,4.1,14),mats.myo);m.rotation.z=Math.PI/2;m.position.set(0,y,z);g.add(m)}for(let i=-3;i<=3;i+=2){const nucleus=new THREE.Mesh(new THREE.SphereGeometry(.11,20,12),new THREE.MeshPhysicalMaterial({color:0x6c4ca0,roughness:.35}));nucleus.scale.set(2.2,.7,.7);nucleus.position.set(i*.48,.6,.1);g.add(nucleus)}const lab=labelSprite('Fibra muscular');lab.position.set(0,1.45,0);g.add(lab);return g}
function buildMyofibril(){const g=new THREE.Group();const shaft=new THREE.Mesh(new THREE.CylinderGeometry(.42,.42,5.1,48),mats.myo);shaft.rotation.z=Math.PI/2;g.add(shaft);for(let i=-5;i<=5;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(.43,i%2===0?.055:.028,10,48),i%2===0?mats.dark:mats.zline);ring.rotation.y=Math.PI/2;ring.position.x=i*.46;g.add(ring)}for(let i=-4;i<=4;i+=2){const band=new THREE.Mesh(new THREE.CylinderGeometry(.435,.435,.3,48),new THREE.MeshPhysicalMaterial({color:0x6f1523,roughness:.35,transparent:true,opacity:.72}));band.rotation.z=Math.PI/2;band.position.x=i*.46;g.add(band)}const lab=labelSprite('Miofibrila');lab.position.set(0,1.35,0);g.add(lab);return g}
function buildSarcomere(){const g=new THREE.Group();const zL=new THREE.Mesh(new THREE.BoxGeometry(.10,2.0,1.2),mats.zline);zL.position.x=-2.4;const zR=zL.clone();zR.position.x=2.4;g.add(zL,zR);for(let row=-4;row<=4;row++){const y=row*.19;for(let depth=-2;depth<=2;depth++){const z=depth*.18;const actL=capsuleBetween(new THREE.Vector3(-2.35,y,z),new THREE.Vector3(-.38,y,z),.025,mats.actin,8);const actR=capsuleBetween(new THREE.Vector3(.38,y,z),new THREE.Vector3(2.35,y,z),.025,mats.actin,8);g.add(actL,actR)}}for(let row=-3;row<=3;row++){const y=row*.22+.03;for(let depth=-1;depth<=1;depth++){const z=depth*.22+.04;const my=capsuleBetween(new THREE.Vector3(-1.45,y,z),new THREE.Vector3(1.45,y,z),.05,mats.myosin,10);g.add(my);for(let x=-1.15;x<=1.15;x+=.38){const head=new THREE.Mesh(new THREE.SphereGeometry(.055,10,8),mats.myosin);head.position.set(x,y+.09,z);g.add(head)}}}const mline=new THREE.Mesh(new THREE.BoxGeometry(.055,1.8,.95),mats.myosin);g.add(mline);const lab=labelSprite('Sarcômero');lab.position.set(0,1.55,0);g.add(lab);return g}

const models=[buildMuscle(),buildFascicle(),buildFiber(),buildMyofibril(),buildSarcomere()];models.forEach((m,i)=>{m.visible=i===0;root.add(m)});
const data=[
{scale:'ESCALA MACROSCÓPICA',step:'01 · MÚSCULO',eye:'Órgão contrátil',title:'Músculo esquelético',text:'Observe o ventre muscular fusiforme e a continuidade com os tendões. O próximo nível revela que o músculo não é uma massa homogênea: ele é organizado em feixes.',tags:['ventre muscular','tendão','fibras paralelas']},
{scale:'ESCALA MESOSCÓPICA',step:'02 · FASCÍCULO',eye:'Feixe organizado',title:'Fascículo muscular',text:'Cada fascículo reúne numerosas fibras musculares e é envolvido por tecido conjuntivo. A organização em feixes distribui forças e mantém a arquitetura interna do músculo.',tags:['perimísio','feixe de fibras','organização interna']},
{scale:'ESCALA CELULAR',step:'03 · FIBRA',eye:'Célula multinucleada',title:'Fibra muscular',text:'A fibra muscular é uma célula longa e multinucleada. Dentro dela existem muitas miofibrilas paralelas, responsáveis pelo padrão estriado e pela produção de força.',tags:['sarcolema','núcleos periféricos','miofibrilas']},
{scale:'ESCALA SUBCELULAR',step:'04 · MIOFIBRILA',eye:'Estrutura contrátil',title:'Miofibrila',text:'A miofibrila contém uma sequência repetitiva de sarcômeros. Essa repetição organiza os filamentos contráteis ao longo do eixo da fibra muscular.',tags:['estriações','unidades em série','filamentos']},
{scale:'ESCALA MOLECULAR',step:'05 · SARCÔMERO',eye:'Unidade contrátil',title:'Sarcômero',text:'Entre duas linhas Z está a unidade contrátil. Actina e miosina se interdigitam; durante a contração, o deslizamento dos filamentos aproxima as linhas Z sem encurtar os próprios filamentos.',tags:['linha Z','actina','miosina','deslizamento']}
];
let current=0,transition=null;
const els={scale:document.getElementById('scaleLabel'),step:document.getElementById('stepLabel'),eye:document.getElementById('infoEyebrow'),title:document.getElementById('infoTitle'),text:document.getElementById('infoText'),tags:document.getElementById('microtags'),prev:document.getElementById('prev'),next:document.getElementById('next')};
function resetCamera(){camera.position.set(0,1.1,current===4?7.8:7.2);controls.target.set(0,0,0);controls.update()}
function setStep(n){n=Math.max(0,Math.min(models.length-1,n));if(n===current)return;const old=models[current],next=models[n];next.visible=true;next.scale.setScalar(.64);next.traverse(o=>{if(o.material&&'opacity'in o.material){}});transition={old,next,t:0};current=n;const d=data[n];els.scale.textContent=d.scale;els.step.textContent=d.step;els.eye.textContent=d.eye;els.title.textContent=d.title;els.text.textContent=d.text;els.tags.innerHTML=d.tags.map(t=>`<span>${t}</span>`).join('');els.prev.disabled=n===0;els.next.disabled=n===models.length-1;els.next.textContent=n===models.length-1?'Unidade contrátil ✓':'Aprofundar →';document.querySelectorAll('.step').forEach((b,i)=>b.classList.toggle('active',i===n));resetCamera()}
document.querySelectorAll('.step').forEach((b,i)=>b.addEventListener('click',()=>setStep(i)));els.prev.addEventListener('click',()=>setStep(current-1));els.next.addEventListener('click',()=>setStep(current+1));document.getElementById('resetView').addEventListener('click',resetCamera);
function resize(){const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
const ro=new ResizeObserver(resize);ro.observe(stage);resize();
const clock=new THREE.Clock();function loop(){requestAnimationFrame(loop);const dt=clock.getDelta();root.rotation.y+=dt*.07;if(transition){transition.t=Math.min(1,transition.t+dt*2.7);const e=1-Math.pow(1-transition.t,3);transition.old.scale.setScalar(1-e*.24);transition.next.scale.setScalar(.64+e*.36);if(transition.t>=1){models.forEach((m,i)=>{m.visible=i===current;m.scale.setScalar(1)});transition=null}}controls.update();renderer.render(scene,camera)}loop();
