import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFExporter } from 'three/addons/exporters/GLTFExporter.js';

const canvas=document.getElementById('scene');
const stage=document.getElementById('stage');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true,powerPreference:'high-performance'});
renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.08;renderer.shadowMap.enabled=true;
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x120c09,.035);
const camera=new THREE.PerspectiveCamera(38,1,.01,100);camera.position.set(0,1.1,7.2);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.055;controls.minDistance=2.3;controls.maxDistance=12;
scene.add(new THREE.HemisphereLight(0xffddbb,0x24140f,2.2));
const key=new THREE.DirectionalLight(0xffc796,4);key.position.set(4,6,5);scene.add(key);const rim=new THREE.DirectionalLight(0xff5a40,2);rim.position.set(-5,1,-4);scene.add(rim);
const root=new THREE.Group();scene.add(root);
const pedestal=new THREE.Mesh(new THREE.CylinderGeometry(2.3,2.5,.12,64),new THREE.MeshStandardMaterial({color:0x1d1410,roughness:.8}));pedestal.position.y=-1.62;scene.add(pedestal);
const M={muscle:new THREE.MeshPhysicalMaterial({color:0xb83c3c,roughness:.42,clearcoat:.2}),deep:new THREE.MeshPhysicalMaterial({color:0x7b171c,roughness:.5}),tendon:new THREE.MeshPhysicalMaterial({color:0xe7d5b6,roughness:.72}),fascia:new THREE.MeshPhysicalMaterial({color:0xf4d7c8,roughness:.45,transparent:true,opacity:.28,side:THREE.DoubleSide}),fiber:new THREE.MeshPhysicalMaterial({color:0xd85d5d,roughness:.4}),fiber2:new THREE.MeshPhysicalMaterial({color:0xef8778,roughness:.4}),myo:new THREE.MeshPhysicalMaterial({color:0xb92b3b,roughness:.36}),actin:new THREE.MeshPhysicalMaterial({color:0xe8c95b,roughness:.32}),myosin:new THREE.MeshPhysicalMaterial({color:0x73b4d1,roughness:.3}),z:new THREE.MeshPhysicalMaterial({color:0xf0e5d2,roughness:.45}),dark:new THREE.MeshStandardMaterial({color:0x4a1016,roughness:.5})};
function cap(a,b,r,mat,rad=20){const d=new THREE.Vector3().subVectors(b,a),len=d.length(),m=new THREE.Mesh(new THREE.CapsuleGeometry(r,Math.max(.001,len-2*r),8,rad),mat);m.position.copy(a).add(b).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),d.normalize());return m}
function muscle(){const g=new THREE.Group();const body=new THREE.Mesh(new THREE.CapsuleGeometry(1.05,2.55,14,64),M.muscle);body.rotation.z=Math.PI/2;body.scale.set(1,1.04,.82);g.add(body,cap(new THREE.Vector3(-2.8,0,0),new THREE.Vector3(-1.75,0,0),.34,M.tendon,28),cap(new THREE.Vector3(1.75,0,0),new THREE.Vector3(2.8,0,0),.34,M.tendon,28));for(let i=-5;i<=5;i++){const c=new THREE.CatmullRomCurve3([new THREE.Vector3(-1.6,i*.05,.72),new THREE.Vector3(0,i*.14,.88),new THREE.Vector3(1.6,i*.05,.72)]);g.add(new THREE.Mesh(new THREE.TubeGeometry(c,48,.018,8,false),M.deep))}return g}
function fascicle(){const g=new THREE.Group();for(let i=0;i<24;i++){const a=i*2.399963,r=.73*Math.sqrt(i/24),y=Math.cos(a)*r,z=Math.sin(a)*r;g.add(cap(new THREE.Vector3(-2.3,y,z),new THREE.Vector3(2.3,y,z),.12,i%3?M.fiber:M.fiber2,14))}const sh=new THREE.Mesh(new THREE.CylinderGeometry(.92,.92,4.9,48,1,true),M.fascia);sh.rotation.z=Math.PI/2;g.add(sh);return g}
function fiber(){const g=new THREE.Group();const cell=new THREE.Mesh(new THREE.CapsuleGeometry(.72,3.4,12,48),M.fiber);cell.rotation.z=Math.PI/2;g.add(cell);for(let i=0;i<16;i++){const a=i*2.399963,r=.48*Math.sqrt((i+1)/16),y=Math.cos(a)*r,z=Math.sin(a)*r,m=new THREE.Mesh(new THREE.CylinderGeometry(.055,.055,4.1,12),M.myo);m.rotation.z=Math.PI/2;m.position.set(0,y,z);g.add(m)}return g}
function myofibril(){const g=new THREE.Group();const s=new THREE.Mesh(new THREE.CylinderGeometry(.42,.42,5.1,40),M.myo);s.rotation.z=Math.PI/2;g.add(s);for(let i=-5;i<=5;i++){const r=new THREE.Mesh(new THREE.TorusGeometry(.43,i%2===0?.055:.028,10,40),i%2===0?M.dark:M.z);r.rotation.y=Math.PI/2;r.position.x=i*.46;g.add(r)}return g}
function sarcomere(){const g=new THREE.Group();const l=new THREE.Mesh(new THREE.BoxGeometry(.10,2,1.2),M.z),r=l.clone();l.position.x=-2.4;r.position.x=2.4;g.add(l,r);for(let y=-.76;y<=.76;y+=.19)for(let z=-.36;z<=.36;z+=.18){g.add(cap(new THREE.Vector3(-2.35,y,z),new THREE.Vector3(-.38,y,z),.025,M.actin,8),cap(new THREE.Vector3(.38,y,z),new THREE.Vector3(2.35,y,z),.025,M.actin,8))}for(let y=-.63;y<=.7;y+=.22)for(let z=-.22;z<=.22;z+=.22)g.add(cap(new THREE.Vector3(-1.45,y,z),new THREE.Vector3(1.45,y,z),.05,M.myosin,10));return g}
const models=[muscle(),fascicle(),fiber(),myofibril(),sarcomere()];models.forEach((m,i)=>{m.visible=i===0;root.add(m)});
const data=[['ESCALA MACROSCÓPICA','01 · MÚSCULO','Órgão contrátil','Músculo esquelético','Observe o ventre muscular e a continuidade com os tendões.','ventre muscular,tendão,fibras'],['ESCALA MESOSCÓPICA','02 · FASCÍCULO','Feixe organizado','Fascículo muscular','O fascículo reúne numerosas fibras musculares envolvidas por tecido conjuntivo.','perimísio,feixe de fibras,organização'],['ESCALA CELULAR','03 · FIBRA','Célula multinucleada','Fibra muscular','A fibra muscular é uma célula longa que contém muitas miofibrilas paralelas.','sarcolema,núcleos,miofibrilas'],['ESCALA SUBCELULAR','04 · MIOFIBRILA','Estrutura contrátil','Miofibrila','A miofibrila contém sarcômeros repetidos em série.','estriações,sarcômeros,filamentos'],['ESCALA MOLECULAR','05 · SARCÔMERO','Unidade contrátil','Sarcômero','Actina e miosina se interdigitam entre duas linhas Z.','linha Z,actina,miosina']];
let current=0,transition=null,arUrl=null;
const E={scale:document.getElementById('scaleLabel'),step:document.getElementById('stepLabel'),eye:document.getElementById('infoEyebrow'),title:document.getElementById('infoTitle'),text:document.getElementById('infoText'),tags:document.getElementById('microtags'),prev:document.getElementById('prev'),next:document.getElementById('next'),ar:document.getElementById('launchAR'),status:document.getElementById('raStatus'),viewer:document.getElementById('arViewer')};
function reset(){camera.position.set(0,1.1,current===4?7.8:7.2);controls.target.set(0,0,0);controls.update()}
function setStep(n){n=Math.max(0,Math.min(4,n));if(n===current)return;const old=models[current],neo=models[n];neo.visible=true;neo.scale.setScalar(.65);transition={old,neo,t:0};current=n;const d=data[n];E.scale.textContent=d[0];E.step.textContent=d[1];E.eye.textContent=d[2];E.title.textContent=d[3];E.text.textContent=d[4];E.tags.innerHTML=d[5].split(',').map(x=>`<span>${x}</span>`).join('');E.prev.disabled=n===0;E.next.disabled=n===4;E.next.textContent=n===4?'Unidade contrátil ✓':'Aprofundar →';document.querySelectorAll('.step').forEach((b,i)=>b.classList.toggle('active',i===n));E.status.textContent='RA pronta para o nível selecionado.';reset()}
document.querySelectorAll('.step').forEach((b,i)=>b.onclick=()=>setStep(i));E.prev.onclick=()=>setStep(current-1);E.next.onclick=()=>setStep(current+1);document.getElementById('resetView').onclick=reset;
function resize(){const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(stage);resize();
const clock=new THREE.Clock();(function loop(){requestAnimationFrame(loop);const dt=clock.getDelta();root.rotation.y+=dt*.07;if(transition){transition.t=Math.min(1,transition.t+dt*2.7);const e=1-Math.pow(1-transition.t,3);transition.old.scale.setScalar(1-e*.25);transition.neo.scale.setScalar(.65+e*.35);if(transition.t>=1){models.forEach((m,i)=>{m.visible=i===current;m.scale.setScalar(1)});transition=null}}controls.update();renderer.render(scene,camera)})();

E.ar.addEventListener('click',async()=>{E.ar.disabled=true;E.status.textContent='Preparando o modelo para RA…';try{const clone=models[current].clone(true);clone.visible=true;const scale=[.12,.16,.18,.22,.25][current];clone.scale.setScalar(scale);clone.rotation.set(0,0,0);clone.position.set(0,0,0);const exp=new GLTFExporter();const buf=await exp.parseAsync(clone,{binary:true,onlyVisible:true});if(arUrl)URL.revokeObjectURL(arUrl);arUrl=URL.createObjectURL(new Blob([buf],{type:'model/gltf-binary'}));E.viewer.src=arUrl;await E.viewer.updateComplete;if(!E.viewer.canActivateAR){E.status.textContent='Modelo preparado, mas este navegador não oferece RA. No iPhone, abra no Safari.';return}E.status.textContent='Abrindo realidade aumentada…';await E.viewer.activateAR()}catch(err){console.error(err);E.status.textContent='Não foi possível iniciar a RA neste navegador.'}finally{E.ar.disabled=false}});
